#!/bin/bash -exu

export GO15VENDOREXPERIMENT=1

ROOT="${PWD}"
diego_release_version="99999+dev.$(date +%s)"

function upload_diego_release() {
  pushd "${ROOT}/diego-release" > /dev/null
    bosh -n create release --force --version ${diego_release_version}
    bosh -n \
      -t ${BOSH_DIRECTOR} \
      upload release --rebase
  popd > /dev/null
}

function deploy_diego() {
  bosh -n \
    -d ./private-credentials/stubs/diego/diego-consul.yml \
    -t ${BOSH_DIRECTOR} \
    deploy
}

function upload_release() {
  local release=${1}
  bosh -t ${BOSH_DIRECTOR} upload release https://bosh.io/d/github.com/cloudfoundry-incubator/${release}
}

function main() {
  upload_release "garden-linux-release"
  upload_release "etcd-release"
  upload_diego_release
  deploy_diego
}

main
