#!/bin/sh
set -eux

export GOPATH="${PWD}/gopath"
export PATH="${GOPATH}/bin":${PATH}

cd "${GOPATH}/src/github.com/cloudfoundry-incubator/route-registrar"

export GOPATH=${PWD}/Godeps/_workspace:${GOPATH}
export PATH=${PWD}/Godeps/_workspace/bin:${PATH}

go get github.com/onsi/ginkgo/ginkgo

./bin/test
