#!/bin/bash
set -eux

root_dir="${PWD}"

# Inputs
MKMAN_DIR="${root_dir}/${MKMAN_DIR:?"\$MKMAN_DIR not set"}"
SPIFF_DIR="${root_dir}/${SPIFF_DIR:?"\$SPIFF_DIR not set"}"
CF_RELEASE_DIR="${root_dir}/${CF_RELEASE_DIR:?"\$CF_RELEASE_DIR not set"}"
export CF_RELEASE_DIR

GOPATH_DIR="${root_dir}/${GOPATH_DIR:?"\$GOPATH_DIR not set"}"
export GOPATH="${GOPATH_DIR}"
export PATH="${GOPATH}/bin":${PATH}

pushd "${SPIFF_DIR}" > /dev/null
  mv spiff* spiff
  chmod +x spiff
popd > /dev/null
export PATH="${SPIFF_DIR}":${PATH}

go get github.com/onsi/ginkgo/ginkgo

pushd "${MKMAN_DIR}" > /dev/null
  ./bin/test
popd > /dev/null

