#!/bin/bash -exu

function main() {
  pushd release > /dev/null
    bosh -n -t ${BOSH_DIRECTOR} create release --force --timestamp-version
    bosh -n -t ${BOSH_DIRECTOR} upload release
  popd > /dev/null
}

main
