#!/bin/bash -exu

function main() {
  pushd release > /dev/null
    bosh -n -t ${BOSH_DIRECTOR} create release --force --timestamp-version --with-tarball
    mv dev_releases/*/*.tgz release.tgz
  popd > /dev/null
}

main
