#!/bin/bash -exu

setup_ruby() {
  set +eu
  source /usr/local/share/chruby/chruby.sh
  chruby 2.2.4
  set -eu
}

generate_deployment_config() {
  local dir="${1}"
  local deployments_dir="${2}"
  local stubs="${@:3}"
  local stubs_array="$(jq -n --arg v "${stubs}" '{ v: $v | split(" ") }' | jq -c .v)"

  cat <<CONFIG
{
  "cf": "integration-latest",
  "consul": "${dir}/consul-release",
  "deployments-dir": "${deployments_dir}",
  "stemcell": "integration-latest",
  "stubs": ${stubs_array}
}
CONFIG
}

preflight_check() {
  set +x
  test -n "${BOSH_DIRECTOR}"
  test -n "${BOSH_USER}"
  test -n "${BOSH_PASSWORD}"
  set -x
}

deploy() {
  bosh \
    -n \
    -t "${1}" \
    -d "${2}" \
    deploy \
    --redact-diff
}

main() {
  preflight_check
  setup_ruby

  generate_deployment_config \
    "${PWD}" \
    "${PWD}" \
    consul-cf-env/stubs/director-uuid.yml \
    consul-cf-env/stubs/cf/diego.yml \
    consul-cf-env/stubs/cf/properties.yml \
    consul-cf-env/stubs/cf/stub.yml \
    > "${PWD}/config.json"

  "${PWD}/cf-deployment/tools/prepare-deployments" \
    "aws" \
    "${PWD}/config.json"

  deploy \
    "${BOSH_DIRECTOR}" \
    "${PWD}/cf.yml"
}

if [ "$(basename "${0}")" = "task" ]; then
  main
fi
