#!/bin/sh

set -eu

fly \
  -t mega \
  sp \
  -p alfredo \
  -c ./pipelines/alfredo.yml \
  -v alfredo-env-private-key="$(cat /Users/pivotal/workspace/alfredo-env/deploy_keys/cloudfoundry/alfredo-env)" \
  -v cf-deployment-private-key="$(cat /Users/pivotal/workspace/mega-ci-env/deploy_keys/cloudfoundry/cf-deployment)" \
  -v alfredo-cf-api="api.alfredo.ci.cf-app.com" \
  -v alfredo-cf-apps-domain="alfredo-apps.ci.cf-app.com" \
  -v alfredo-cf-admin-password="badlemur64" \
  -l ~/workspace/alfredo-env/pipeline_vars/alfredo.yml  \
  -l ~/workspace/alfredo-env/pipeline_vars/alfredo-buckets.yml 
