#!/bin/sh

set -eu

fly \
  -t mega \
  sp \
  -p cf-release \
  -c ./pipelines/cf-release.yml \
  -v cf-release-private-key="$(cat /Users/pivotal/workspace/mega-ci-env/deploy_keys/cloudfoundry/cf-release)" \
  -v cf-release-credentials-private-key="$(cat /Users/pivotal/workspace/mega-ci-env/deploy_keys/cloudfoundry/cf-release-credentials)"
