#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

pushd release-repo
  git config user.name "CF MEGA BOT"
  git config user.email "cf-mega@pivotal.io"

  git remote add -f master-repo ../release-repo-master
  git merge "master-repo/master" -m 'Merge with master'

  git status
  git show --color | cat

  ./scripts/generate_blessed_versions \
      ../stemcell/*.tgz \
      ../cf-release \
      ../etcd-release/*.tgz \
      ../consul-release/*.tgz

  git status
  git show --color | cat
popd

cp -r release-repo $BLESSED_REPO/release-repo
