#!/bin/bash -exu

ROOT="${PWD}"
CURRENT_TIME=$(date +%s)
STATE_DIR="${ROOT}/bbl-integration-s3/${CURRENT_TIME}"

function install_bosh_cli() {
  pushd "${ROOT}" > /dev/null
    wget https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-0.0.69-linux-amd64
    mv bosh-cli-0.0.69-linux-amd64 /usr/local/bin/bosh
    chmod +x /usr/local/bin/bosh
  popd > /dev/null
}

function main() {
  install_bosh_cli

  mkdir -p "${GOPATH}/src/github.com/cloudfoundry"
  mkdir -p "${STATE_DIR}"

  pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
    ln -s "${ROOT}/bosh-bootloader"
    set +x
    cat > bit_config.json << EOF
    {
      "AWSAccessKeyID": "${AWS_ACCESS_KEY_ID}",
      "AWSSecretAccessKey": "${AWS_SECRET_ACCESS_KEY}",
      "AWSRegion": "${AWS_REGION}",
      "StateFileDir": "${STATE_DIR}"
    }
EOF
    set -x
    BIT_CONFIG=$PWD/bit_config.json ./bosh-bootloader/scripts/aws_integration_tests
  popd > /dev/null
}

function finish() {
  pushd "${ROOT}/bbl-integration-s3" > /dev/null
    tar -cvzf "${CURRENT_TIME}.tgz" "${CURRENT_TIME}"
  popd > /dev/null
}
trap finish EXIT

main
