#!/bin/bash -exu

ROOT="${PWD}"
CURRENT_TIME=$(date +%s)
STATE_DIR="${ROOT}/bbl-integration-s3/${CURRENT_TIME}"

function main() {
  mkdir -p "${GOPATH}/src/github.com/pivotal-cf-experimental"

  mkdir -p "${STATE_DIR}"

  pushd "${GOPATH}/src/github.com/pivotal-cf-experimental" > /dev/null
    ln -s "${ROOT}/bosh-bootloader"
    set +x
    cat > bit_config.json << EOF
    {
      "AWSAccessKeyID": "$AWS_ACCESS_KEY_ID",
      "AWSSecretAccessKey": "$AWS_SECRET_ACCESS_KEY",
      "AWSRegion": "$AWS_REGION",
      "StateFileDir": "${STATE_DIR}"
    }
EOF
    set -x
    BIT_CONFIG=$PWD/bit_config.json ./bosh-bootloader/scripts/concourse_integration_tests
  popd > /dev/null
}

function finish() {
  if [ ! "$(ls -A ${STATE_DIR})" ]; then
       echo "no assets to save"
  else
    pushd "${ROOT}/bbl-integration-s3" > /dev/null
      tar -cvzf "${CURRENT_TIME}.tgz" "${CURRENT_TIME}"
    popd > /dev/null
  fi
}
trap finish EXIT

main
