#!/bin/bash -exu

ROOT="${PWD}"
CURRENT_TIME=$(date +%s)
STATE_DIR="${ROOT}/bbl-integration-s3/${CURRENT_TIME}"

function main() {
  mkdir -p "${GOPATH}/src/github.com/cloudfoundry"

  mkdir -p "${STATE_DIR}"

  pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
    ln -s "${ROOT}/bosh-bootloader"

    ./bosh-bootloader/scripts/concourse_integration_tests
  popd > /dev/null
}

function finish() {
  pushd "${ROOT}/bbl-integration-s3" > /dev/null
    tar -cvzf "${CURRENT_TIME}.tgz" "${CURRENT_TIME}"
  popd > /dev/null
}
trap finish EXIT

main
