#!/bin/bash -exu

ROOT="${PWD}"

mkdir -p "${GOPATH}/src/github.com/pivotal-cf-experimental"

pushd "${GOPATH}/src/github.com/pivotal-cf-experimental" > /dev/null
  ln -s "${ROOT}/bosh-bootloader"
  set +x
  cat > bit_config.json << EOF
  {
    "AWSAccessKeyID": "$AWS_ACCESS_KEY_ID",
    "AWSSecretAccessKey": "$AWS_SECRET_ACCESS_KEY",
    "AWSRegion": "$AWS_REGION"
  }
EOF
  set -x
  BIT_CONFIG=$PWD/bit_config.json ./bosh-bootloader/scripts/integration_tests
popd > /dev/null
