#!/bin/bash -exu

ROOT="${PWD}"
CURRENT_TIME=$(date +%s)
STATE_DIR="${ROOT}/bbl-integration-s3/${CURRENT_TIME}"


function install_bosh_cli() {
  pushd "${ROOT}" > /dev/null
    wget https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-0.0.69-linux-amd64
    mv bosh-cli-0.0.69-linux-amd64 /usr/local/bin/bosh
    chmod +x /usr/local/bin/bosh
  popd > /dev/null
}

function main() {
  install_bosh_cli

  pushd "${ROOT}/bosh-aws-cpi-release" > /dev/null
    export BOSH_AWS_CPI_URL=$(cat url)
    export BOSH_AWS_CPI_SHA1=$(cat sha1)
  popd > /dev/null

  pushd "${ROOT}/stemcell" > /dev/null
    export STEMCELL_URL="$(cat url)"
    export STEMCELL_SHA1="$(cat sha1)"
  popd > /dev/null

  pushd "${ROOT}/bbl-compiled-bosh-release-s3" > /dev/null
    export BOSH_URL="$(cat url)"
    local release_name
    release_name=$(cat url | cut -f 5 -d"/")
    export BOSH_SHA1="$(sha1sum ${release_name} | cut -f1 -d" ")"
  popd > /dev/null

  mkdir -p "${GOPATH}/src/github.com/cloudfoundry"

  mkdir -p "${STATE_DIR}"

  pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
    ln -s "${ROOT}/bosh-bootloader"
    set +x
    cat > bit_config.json << EOF
    {
      "AWSAccessKeyID": "${AWS_ACCESS_KEY_ID}",
      "AWSSecretAccessKey": "${AWS_SECRET_ACCESS_KEY}",
      "AWSRegion": "${AWS_REGION}",
      "StateFileDir": "${STATE_DIR}"
    }
EOF
    set -x
    BIT_CONFIG=$PWD/bit_config.json ./bosh-bootloader/scripts/integration_tests
  popd > /dev/null
}

function finish() {
  pushd "${ROOT}/bbl-integration-s3" > /dev/null
    tar -cvzf "${CURRENT_TIME}.tgz" "${CURRENT_TIME}"
  popd > /dev/null
}
trap finish EXIT

main
