#!/bin/bash -exu

ROOT="${PWD}"

mkdir -p "${GOPATH}/src/github.com/cloudfoundry"

pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
  ln -s "${ROOT}/bosh-bootloader"
  chpst -u testuser:testuser ./bosh-bootloader/scripts/test
popd > /dev/null
