#!/bin/bash -exu

setup_ruby() {
  set +eu
  source /usr/local/share/chruby/chruby.sh
  chruby 2.2.4
  set -eu
}

generate_deployment_config() {
  local dir="${1}"
  local deployments_dir="${2}"
  local stubs="${@:3}"
  local stubs_array="$(jq -n --arg v "${stubs}" '{ v: $v | split(" ") }' | jq -c .v)"

  cat <<CONFIG
{
	"cf": "integration-latest",
	"etcd": "${dir}/etcd-release",
	"deployments-dir": "${deployments_dir}",
	"stemcell": "integration-latest",
	"stubs": ${stubs_array}
}
CONFIG
}

deploy() {
  bosh \
    -n \
    -t "${1}" \
    -d "${2}" \
    deploy \
    --redact-diff
}

preflight_check() {
	set +x
	test -n "${BOSH_DIRECTOR}"
	test -n "${BOSH_USER}"
	test -n "${BOSH_PASSWORD}"
	set -x
}

main() {
  preflight_check
  setup_ruby

  local stub_path
  stub_path="${PWD}/${STUB_PATH}"

  local stub_parts_path
  stub_parts_path="${PWD}/${STUB_PARTS_PATH}"

  local stubs
  stubs=("${stub_path} $(ls "${stub_parts_path}/"*)")

  generate_deployment_config \
	  "${PWD}" \
	  "${PWD}" \
	  ${stubs[@]} \
	  > "${PWD}/config.json"

  "${PWD}/cf-deployment/tools/prepare-deployments" \
	  "aws" \
	  "${PWD}/config.json"

  deploy \
	  "${BOSH_DIRECTOR}" \
	  "${PWD}/cf.yml"
}

if [ "$(basename "${0}")" = "task" ]; then
	main
fi
