#!/bin/bash -exu

generate_deployment_config() {
  local dir="${1}"
  local deployments_dir="${2}"
  local stubs="${@:3}"
  local stubs_array="$(jq -n --arg v "${stubs}" '{ v: $v | split(" ") }' | jq -c .v)"
  local stemcell_location="$(ls "${dir}/stemcell/"*.tgz | head -n 1)"

  cat <<CONFIG
{
	"cf": "${dir}/cf-release",
	"etcd": "${dir}/etcd-release",
	"stemcell": "${stemcell_location}",
	"deployments-dir": "${deployments_dir}",
	"stubs": ${stubs_array}
}
CONFIG
}

deploy() {
  bosh \
    -t "${1}" \
    -u "${2}" \
    -p "${3}" \
    -d "${4}" \
    deploy
}

main() {
  local stubs
  stubs=("${STUB_PATH} $(ls "${STUB_PARTS_PATH}/"*)")

  generate_deployment_config \
	  "${PWD}" \
	  "${PWD}" \
	  ${stubs[@]} \
	  > "${PWD}/config.json"

  "${PWD}/cf-deployment/tools/prepare-deployments" \
	  "aws" \
	  "${PWD}/config.json"

  deploy \
    "${BOSH_DIRECTOR}" \
    "${BOSH_USER}" \
    "${BOSH_PASSWORD}" \
    "${PWD}/cf.yml"
}

if [ "$(basename "${0}")" = "task" ]; then
	main
fi
