#!/bin/bash -exu

function main() {

  cf api api.$CF_DOMAIN --skip-ssl-validation

  set +x
  cf auth $CF_USER $CF_PASSWORD
  set -x

  cf enable-feature-flag diego_docker

  bosh -t $BOSH_DIRECTOR download manifest $DEPLOYMENT_NAME manifest.yml

  bosh -n --color -t $BOSH_DIRECTOR -d manifest.yml run errand acceptance_tests
}

main
