#!/bin/bash -exu

ROOT=${PWD}
BBL_VERSION=$(cat "${ROOT}/bbl-version/number")

function main() {
  local commit_sha

  mkdir -p "${GOPATH}/src/github.com/cloudfoundry/"
  ln -s "${ROOT}/bosh-bootloader" "${GOPATH}/src/github.com/cloudfoundry/"
  commit_sha=$(git -C "${ROOT}/bosh-bootloader" rev-parse HEAD)

  pushd "${GOPATH}/src/github.com/cloudfoundry/bosh-bootloader/bbl" > /dev/null
    build_bbl
  popd > /dev/null

  pushd "${ROOT}/builds" > /dev/null
    echo -n "v${BBL_VERSION}" > name
    echo -n "${commit_sha}" > commitish
  popd > /dev/null
}

function build_bbl() {
  echo "Building 64-bit Darwin"
  GOARCH=amd64 GOOS=darwin \
    go build \
    -ldflags "-X main.Version=${BBL_VERSION}" \
    -o "${ROOT}/builds/bin/bbl-v${BBL_VERSION}_osx" .
}

main
