#!/bin/bash
set -e -x

source ~/.bashrc

root_dir=${PWD}

# Outputs
LOGS_DIR="${PWD}/${LOGS_DIR}"

set +x
source ./private-credentials/$ENVIRONMENT/bosh_environment
set -x

bosh -t $BOSH_DIRECTOR download manifest $DEPLOYMENT_NAME manifest.yml

bosh -n --color -t $BOSH_DIRECTOR -d manifest.yml run errand acceptance_tests --download-logs --logs-dir $LOGS_DIR
