#!/bin/bash

set -x

source ~/.bashrc

echo "Sourcing bosh environment"

set +x
source deployments-runtime/mega-ci/bosh_environment
set -x

bosh target $BOSH_DIRECTOR

echo "Cleaning etcd deployments"
etcd_deployments=$(bosh deployments | grep 'etcd-[A-Za-z0-9]\{8\}-[A-Za-z0-9]\{4\}-[A-Za-z0-9]\{4\}-[A-Za-z0-9]\{4\}-[A-Za-z0-9]\{12\}' | awk '{print $2}')
for i in $etcd_deployments; do
  echo $i
done

echo "Cleaning turbulence deployments"
turbulence_deployments=$(bosh deployments | grep 'turbulence-[A-Za-z0-9]\{8\}-[A-Za-z0-9]\{4\}-[A-Za-z0-9]\{4\}-[A-Za-z0-9]\{4\}-[A-Za-z0-9]\{12\}' | awk '{print $2}')
for i in $turbulence_deployments; do
  echo $i
done

echo "Cleaning all unused releases"
bosh clean --all
