#!/bin/bash
set -e -x

source ~/.bashrc

cd release-repo

git config user.name "CF MEGA BOT"
git config user.email "cf-mega@pivotal.io"
git merge origin/master -m 'Merge with master'

./scripts/generate_blessed_versions ../stemcell/*.tgz ../cf-release ../etcd-release/*.tgz