#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

pushd release-repo
  git config user.name "CF MEGA BOT"
  git config user.email "cf-mega@pivotal.io"
  git merge origin/master -m 'Merge with master'

  git status
  git show

  ./scripts/generate_blessed_versions \
      ../stemcell/*.tgz \
      ../cf-release \
      ../etcd-release/*.tgz

  git status
  git show
popd
