#!/bin/bash
set -e -x

source ~/.bashrc

cd release-repo

cp ../runtime-credentials/$PRIVATE_YML_PATH ./config

for i in {1..5}; do
  bosh -n create release --with-tarball --final
  EXIT_STATUS=${PIPESTATUS[0]}
  if [ "$EXIT_STATUS" = "0" ]; then
    break
  fi
done

if [ ! "$EXIT_STATUS" = "0" ]; then
  echo "Failed to Create $RELEASE_NAME Release"
  exit $EXIT_STATUS
fi

new_release_version=$(find releases -regex ".*${RELEASE_NAME}-[0-9]*.yml" | sort | tail -n 1 | egrep -o "${RELEASE_NAME}-[0-9]+" | egrep -o "[0-9]+")

git add .final_builds releases
git config user.name "CF MEGA BOT"
git config user.email "cf-mega@pivotal.io"
git commit -m "Final release ${new_release_version}"
commit_sha=$(git rev-parse HEAD)

git checkout master
git merge --ff-only ${commit_sha}

git checkout develop
git merge master -m "Merge final release ${new_release_version}"

git checkout master

echo ${new_release_version} > version_number
