#!/bin/bash
set -e -x

source ~/.bashrc
source ./deployments-runtime/${ENVIRONMENT}/bosh_environment

bosh target $BOSH_DIRECTOR
bosh upload stemcell stemcell/*.tgz --skip-if-exists

spiff merge ./mega-ci/templates/bosh/bosh-deployment.yml $STUB_PATH $STUB_PARTS_PATH/* > stub.yml

cd cf-deployment

pushd ../cf-release
  for i in `seq 1 5`;
  do
    bosh -n --parallel 10 sync blobs && break
  done
popd

./scripts/deploy aws ../cf-release ../etcd-release/*.tgz ../stub.yml

cat outputs/manifests/cf.yml
