#!/bin/bash
set -e -x

source ~/.bashrc
set +x
source ./deployments-runtime/mega-ci/bosh_environment
set -x

bosh target $BOSH_DIRECTOR
bosh upload stemcell stemcell/*.tgz --skip-if-exists

spiff merge ./mega-ci/templates/cf/cf-stub-mask.yml $STUB_PATH $STUB_PARTS_PATH/* > stub.yml

cd cf-deployment

pushd ../cf-release
  for i in `seq 1 5`;
  do
    bosh -n --parallel 10 sync blobs && break
  done
popd

pushd ../etcd-release
  for i in `seq 1 5`;
  do
    bosh -n --parallel 10 sync blobs && break
  done
popd

./scripts/deploy aws ../cf-release ../etcd-release ../consul-release ../stub.yml

cat outputs/manifests/cf.yml
