#!/bin/bash -exu

./mega-ci/scripts/setup_aws_bosh_for_concourse "mega-ci-env"

git config user.name "CF MEGA BOT"
git config user.email "cf-mega@pivotal.io"

pushd mega-ci-env > /dev/null
  git checkout master
  git add artifacts/deployments/bosh-state.json
  git commit -m "Update bosh-state.json"
popd > /dev/null

shopt -s dotglob
cp -R mega-ci-env/* mega-ci-env-out
