#!/bin/bash -exu

./mega-ci/scripts/setup_aws_bosh_for_concourse "mega-ci-env"

git config --global user.email "cf-infrastructure@pivotal.io"
git config --global user.name "bootload-mega-ci"

pushd mega-ci-env > /dev/null
  git checkout master
  git add artifacts/deployments/bosh-state.json
  git commit -m "Update bosh-state.json"
popd
