---
platform: linux

image: docker:///cloudfoundry/runtime-ci

inputs:
  - name: mega-ci
  - name: deployments-runtime

run:
  path: mega-ci/scripts/ci/generate-iaas-settings

params:
  DEPLOYMENT_DIR:
  DEPLOYMENT:
  SECURITY_GROUP:
  STACK_NAME:
