#!/bin/bash

set -e -x

source ~/.bashrc

source deployments-runtime/$DEPLOYMENT_DIR/aws_environment

mkdir generated-stubs

aws cloudformation describe-stack-resources --stack-name $STACK_NAME \
  | jq '.StackResources|map({key: .LogicalResourceId, value: .PhysicalResourceId}) | from_entries as $body | {Resources: $body}' \
  > generated-stubs/aws-resources.json

SECURITY_GROUP_ID=$(cat generated-stubs/aws-resources.json | jq -r .Resources.${SECURITY_GROUP})
SECURITY_GROUP_NAME=$(aws ec2 describe-security-groups --group-ids ${SECURITY_GROUP_ID} | jq -r .SecurityGroups[0].GroupName)

SUBNET_ID=$(cat generated-stubs/aws-resources.json | jq -r .Resources.$SUBNET)
AWS_ZONE=$(aws ec2 describe-subnets --subnet-ids $SUBNET_ID | jq -r .Subnets[0].AvailabilityZone)

cat > generated-stubs/security-groups.yml <<EOF
{
  "SecurityGroups": {
    "$SECURITY_GROUP": "$SECURITY_GROUP_NAME"
  },
  "AvailabilityZones": {
    "$SUBNET": "$AWS_ZONE"
  }
}
EOF

spiff merge mega-ci/templates/$DEPLOYMENT/iaas-settings.yml \
  generated-stubs/aws-resources.json \
  generated-stubs/security-groups.yml \
  > generated-stubs/iaas-settings.yml

cat generated-stubs/iaas-settings.yml
