#!/bin/bash
set -ex

MASTER_BRANCH="${MASTER_BRANCH:-master}"

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

pushd release-repo
  git config user.name "CF MEGA BOT"
  git config user.email "cf-mega@pivotal.io"

  git remote add -f master-repo ../release-repo-master
  git merge --no-edit "master-repo/${MASTER_BRANCH}"

  git status
  git show --color | cat
popd
