#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

pushd release-repo
  git config user.name "CF MEGA BOT"
  git config user.email "cf-mega@pivotal.io"
  git merge --no-edit origin/master

  git status
  git show
popd
