#!/bin/bash
set -e -x

source ~/.bashrc

spiff merge ./mega-ci/templates/bosh/bosh-deployment.yml $STUB_PATH $STUB_PARTS_PATH/* > stub.yml

cd cf-deployment

mkdir -p outputs/manifests

pushd ../cf-release
  for i in `seq 1 5`;
  do
    bosh -n --parallel 10 sync blobs && break
  done
popd

pushd ../etcd-release
  for i in `seq 1 5`;
  do
    bosh -n --parallel 10 sync blobs && break
  done
popd

./scripts/prepare_deployment aws ../cf-release ../etcd-release ../stub.yml > outputs/manifests/cf.yml

cat outputs/manifests/cf.yml
