#!/bin/bash
set -e -x

source ~/.bashrc

spiff merge $STUB_PATH $STUB_PARTS_PATH/* > stub.yml

cd cf-deployment

mkdir -p outputs/manifests

./scripts/prepare_deployment aws ../cf-release ../etcd-release ../stub.yml > outputs/manifests/cf.yml
