#!/bin/bash
set -e -x

source ~/.bashrc

set +x
source ./private-credentials/$ENVIRONMENT/bosh_environment
set -x

if [ -n "$LOGS_DIR" ]; then
  mkdir $LOGS_DIR
fi

bosh -t $BOSH_DIRECTOR download manifest $DEPLOYMENT_NAME manifest.yml

bosh -n --color -t $BOSH_DIRECTOR -d manifest.yml $COMMAND
