#!/bin/bash
set -e -x

source ~/.bashrc

cd release

RELEASE_OUT="../create-release.out"
for i in {1..5}; do
  echo "Syncing blobs, attempt $i"
  bosh -n --parallel 10 sync blobs && break
done

for i in {1..5}; do
  echo "Creating release, attempt $i"
  bosh -n create release --with-tarball | tee -a $RELEASE_OUT
  EXIT_STATUS=${PIPESTATUS[0]}
  if [ "$EXIT_STATUS" = "0" ]; then
    break
  fi
done

if [ ! "$EXIT_STATUS" = "0" ]; then
  echo "Failed to Create Release"
  exit $EXIT_STATUS
fi

MANIFEST_YML=`grep -a "Release manifest" $RELEASE_OUT  | cut -d " " -f3`
if [ "$MANIFEST_YML" = "" ]; then
  echo "No Release Manifest Found"
  exit 1
fi

TARBALL=`grep -a "Release tarball" $RELEASE_OUT | cut -d " " -f4`
if [ "$TARBALL" = "" ]; then
  echo "No Release Tarball Found"
  exit 1
fi

rm -rf ./.blobs

mkdir -p output

mv $MANIFEST_YML ./output/manifest.yml
mv $TARBALL ./output/$RELEASE_NAME-${COMMIT_SHA}.tgz
mv $RELEASE_OUT ./output/

