#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

pushd cf-deployment
  bundle install
  bundle exec rspec
popd
