#!/bin/bash -exu

export GO15VENDOREXPERIMENT=1

ROOT="${PWD}"
release_version="99999+dev.$(date +%s)"

function upload_release() {
  local release_path="$1"

  pushd "${ROOT}/${release_path}" > /dev/null
    /opt/rubies/ruby-2.2.4/bin/bosh -n create release --force --version ${release_version}
    /opt/rubies/ruby-2.2.4/bin/bosh -n -t ${BOSH_DIRECTOR} upload release --rebase
  popd > /dev/null
}

function deploy_etcd() {
  set +ux
  source ~/.bashrc
  set -ux

  mkdir -p "${GOPATH}/src/github.com/cloudfoundry"
  pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
    ln -s "${ROOT}/mega-ci"
    pushd ./mega-ci/scripts/ci/deploy-aws-manifests > /dev/null
      set +x
      go run main.go \
        --manifest-path "${ROOT}/release/${MANIFEST_PATH}" \
        --director "${BOSH_DIRECTOR}" \
        --user "${BOSH_USER}" \
        --password "${BOSH_PASSWORD}" \
        --aws-access-key-id "${AWS_ACCESS_KEY_ID}" \
        --aws-secret-access-key "${AWS_SECRET_ACCESS_KEY}" \
        --aws-region "${AWS_DEFAULT_REGION}"
      set -x
    popd > /dev/null
  popd > /dev/null
}

function main() {
  local etcd_release_path="release"
  local consul_release_path="consul-release"

  upload_release "${consul_release_path}"
  upload_release "${etcd_release_path}"
  deploy_etcd
}

function teardown() {
  set +e
  /opt/rubies/ruby-2.2.4/bin/bosh -n -t ${BOSH_DIRECTOR} delete release consul ${release_version}
  /opt/rubies/ruby-2.2.4/bin/bosh -n -t ${BOSH_DIRECTOR} delete release etcd ${release_version}
  set -e
}

trap teardown EXIT

main
