#!/bin/bash -exu

ROOT="${PWD}"

mkdir -p "${GOPATH}/src/github.com/pivotal-cf-experimental"

pushd "${GOPATH}/src/github.com/pivotal-cf-experimental" > /dev/null
  ln -s "${ROOT}/bosh-test"
  ./bosh-test/scripts/test
popd > /dev/null
