groups:
- name: alfredo
  jobs:
  - deploy-and-test-alfredo

resources:
- name: deployments-runtime
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/deployments-runtime.git
- name: etcd-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/etcd-release
- name: mega-ci
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/mega-ci.git
- name: cf-release
  type: git
  source:
    branch: develop
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/cf-release.git
- name: cf-deployment
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/cf-deployment.git
- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
- name: acceptance-tests-logs
  type: s3
  source:
    bucket: {{logs_bucket}}
    regexp: acceptance_tests.*.tgz
    access_key_id: {{access_key}}
    secret_access_key: {{secret_key}}
jobs:
- name: deploy-and-test-alfredo
  public: false
  serial: true
  plan:
  - aggregate:
    - get: deployments-runtime
    - get: mega-ci
    - get: cf-release
      trigger: true
    - get: etcd-release
      trigger: true
    - get: cf-deployment
    - get: stemcell
      resource: aws-stemcell
  - task: deploy-cf
    file: mega-ci/scripts/ci/deploy-cf.yml
    config:
      params:
        ENVIRONMENT: alfredo
        STUB_PATH: deployments-runtime/alfredo/stubs/cf/cf-stub.yml
        STUB_PARTS_PATH: deployments-runtime/alfredo/generated-stubs/cf
  - task: cleanup
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        ENVIRONMENT: alfredo
        DEPLOYMENT_NAME: cf-alfredo
        COMMAND: cleanup
  - task: smoke-tests
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        COMMAND: 'run errand smoke_tests'
        DEPLOYMENT_NAME: cf-alfredo
        ENVIRONMENT: alfredo
  - task: acceptance-tests-1
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        COMMAND: run errand acceptance_tests --download-logs --logs-dir acceptance-tests-1
        DEPLOYMENT_NAME: cf-alfredo
        ENVIRONMENT: alfredo
        LOGS_DIR: acceptance-tests-1
    ensure:
      put: acceptance-tests-logs
      params:
        from: acceptance-tests-1/acceptance_tests(.*).tgz
  - task: acceptance-tests-2
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        COMMAND: run errand acceptance_tests --download-logs --logs-dir acceptance-tests-2
        DEPLOYMENT_NAME: cf-alfredo
        ENVIRONMENT: alfredo
        LOGS_DIR: acceptance-tests-2
    ensure:
      put: acceptance-tests-logs
      params:
        from: acceptance-tests-2/acceptance_tests(.*).tgz
  - task: acceptance-tests-3
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        COMMAND: run errand acceptance_tests --download-logs --logs-dir acceptance-tests-3
        DEPLOYMENT_NAME: cf-alfredo
        ENVIRONMENT: alfredo
        LOGS_DIR: acceptance-tests-3
    ensure:
      put: acceptance-tests-logs
      params:
        from: acceptance-tests-3/acceptance_tests(.*).tgz
