groups:
- name: alfredo
  jobs:
  - cf-deployment-unit-tests
  - deploy-and-test-alfredo
  - bless
  - merge-master-into-develop

resources:
- name: deployments-runtime
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/deployments-runtime.git
- name: etcd-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/etcd-release
- name: consul-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/consul-release
- name: mega-ci
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/mega-ci.git
- name: cf-release
  type: git
  source:
    branch: runtime-passed
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/cf-release.git
- name: cf-deployment-master
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/cf-deployment.git
- name: cf-deployment-develop
  type: git
  source:
    branch: develop
    ignore_paths: [blessed_versions.json]
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/cf-deployment.git
- name: cf-deployment-develop-merge-target
  type: git
  source:
    branch: develop
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/cf-deployment.git
- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
- name: acceptance-tests-logs
  type: s3
  source:
    bucket: {{logs_bucket}}
    regexp: acceptance_tests.*.tgz
    access_key_id: {{access_key}}
    secret_access_key: {{secret_key}}
jobs:
- name: cf-deployment-unit-tests
  public: false
  plan:
  - aggregate:
    - get: cf-deployment
      resource: cf-deployment-develop
      trigger: true
    - get: mega-ci
  - task: unit-tests
    file: mega-ci/scripts/ci/unit-tests-cf-deployment.yml
    config:
      params:
        CF_DEPLOYMENT_TRACE: true

- name: deploy-and-test-alfredo
  public: false
  serial: true
  plan:
  - aggregate:
    - get: deployments-runtime
    - get: mega-ci
    - get: cf-release
      trigger: true
    - get: etcd-release
      trigger: true
    - get: cf-deployment
      resource: cf-deployment-develop
      trigger: true
      passed: [cf-deployment-unit-tests]
    - get: stemcell
      resource: aws-stemcell
      trigger: true
    - get: consul-release
      trigger: true
  - task: deploy-cf
    file: mega-ci/scripts/ci/deploy-cf.yml
    config:
      params:
        ENVIRONMENT: alfredo
        STUB_PATH: deployments-runtime/alfredo/stubs/cf/cf-stub.yml
        STUB_PARTS_PATH: deployments-runtime/alfredo/generated-stubs/cf
  - task: cleanup
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        ENVIRONMENT: alfredo
        DEPLOYMENT_NAME: cf-alfredo
        COMMAND: cleanup
  - task: smoke-tests
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        COMMAND: 'run errand smoke_tests'
        DEPLOYMENT_NAME: cf-alfredo
        ENVIRONMENT: alfredo
  - task: acceptance-tests-1
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        COMMAND: run errand acceptance_tests --download-logs --logs-dir acceptance-tests-1
        DEPLOYMENT_NAME: cf-alfredo
        ENVIRONMENT: alfredo
        LOGS_DIR: acceptance-tests-1
    ensure:
      put: acceptance-tests-logs
      params:
        from: acceptance-tests-1/acceptance_tests(.*).tgz
  - task: acceptance-tests-2
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        COMMAND: run errand acceptance_tests --download-logs --logs-dir acceptance-tests-2
        DEPLOYMENT_NAME: cf-alfredo
        ENVIRONMENT: alfredo
        LOGS_DIR: acceptance-tests-2
    ensure:
      put: acceptance-tests-logs
      params:
        from: acceptance-tests-2/acceptance_tests(.*).tgz
  - task: acceptance-tests-3
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        COMMAND: run errand acceptance_tests --download-logs --logs-dir acceptance-tests-3
        DEPLOYMENT_NAME: cf-alfredo
        ENVIRONMENT: alfredo
        LOGS_DIR: acceptance-tests-3
    ensure:
      put: acceptance-tests-logs
      params:
        from: acceptance-tests-3/acceptance_tests(.*).tgz
- name: bless
  public: false
  serial: true
  plan:
  - aggregate:
    - get: deployments-runtime
    - get: mega-ci
    - get: cf-release
      passed: [deploy-and-test-alfredo]
      trigger: true
    - get: etcd-release
      passed: [deploy-and-test-alfredo]
      trigger: true
    - get: release-repo
      resource: cf-deployment-develop
      passed: [deploy-and-test-alfredo]
      trigger: true
    - get: release-repo-master
      resource: cf-deployment-master
    - get: stemcell
      resource: aws-stemcell
      passed: [deploy-and-test-alfredo]
      trigger: true
    - get: consul-release
      passed: [deploy-and-test-alfredo]
      trigger: true
  - task: commit-blessing
    file: mega-ci/scripts/ci/commit-blessing.yml
  - put: cf-deployment-master
    params:
      repository: commit-blessing/release-repo
- name: merge-master-into-develop
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: release-repo-master
      resource: cf-deployment-master
      trigger: true
    - get: release-repo
      resource: cf-deployment-develop-merge-target
      params: {fetch: [master]}
  - task: merge-master-into-develop
    file: mega-ci/scripts/ci/merge-master-into-develop.yml
  - put: cf-deployment-develop-merge-target
    params:
      repository: merge-master-into-develop/release-repo
