groups:
- name: alfredo
  jobs:
  - deploy-and-test-alfredo

resources:
- name: deployments-runtime
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/deployments-runtime.git
- name: etcd-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/etcd-release
- name: mega-ci
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/mega-ci.git
- name: cf-release
  type: git
  source:
    branch: develop
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/cf-release.git
- name: cf-deployment
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/cf-deployment.git
- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

jobs:
- name: deploy-and-test-alfredo
  public: false
  serial: true
  plan:
  - aggregate:
    - get: deployments-runtime
    - get: mega-ci
    - get: cf-release
      trigger: true
    - get: etcd-release
      trigger: true
    - get: cf-deployment
    - get: stemcell
      resource: aws-stemcell
  - task: deploy-cf
    file: mega-ci/scripts/ci/deploy-cf.yml
    config:
      params:
        ENVIRONMENT: alfredo
        STUB_PATH: deployments-runtime/alfredo/stubs/cf/cf-stub.yml
        STUB_PARTS_PATH: deployments-runtime/alfredo/generated-stubs/cf
  - task: cleanup
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        ENVIRONMENT: alfredo
        DEPLOYMENT_NAME: cf-alfredo
        COMMAND: cleanup
  - task: run-cats
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        ENVIRONMENT: alfredo
        DEPLOYMENT_NAME: cf-alfredo
        COMMAND: run errand acceptance_tests
