groups:
- name: bootload-mega-ci
  jobs:
  - deploy-mega-ci-bosh

resources:
- name: mega-ci-env
  type: git
  source:
    branch: master
    private_key: {{mega-ci-env-writable-private-key}}
    uri: git@github.com:cloudfoundry/mega-ci-env.git
- name: mega-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/mega-ci.git

jobs:
- name: deploy-mega-ci-bosh
  public: true
  plan:
  - aggregate:
    - get: mega-ci-env
    - get: mega-ci
  - task: deploy-bosh
    file: mega-ci/scripts/ci/deploy-bosh.yml
  - put: mega-ci-env
    params:
      repository: mega-ci-env-out
