groups:
- name: bosh-bootloader
  jobs:
  - test-bosh-bootloader

resources:
- name: bosh-bootloader
  type: git
  source:
    branch: master
    uri: https://github.com/pivotal-cf-experimental/bosh-bootloader.git
- name: mega-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/mega-ci.git

jobs:
- name: test-bosh-bootloader
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: bosh-bootloader
      trigger: true
  - task: test
    file: mega-ci/scripts/ci/bosh-bootloader/test.yml
