groups:
- name: bosh-bootloader
  jobs:
  - build-compiled-bosh-release
  - update-release-constants
  - test-bosh-bootloader
  - integration-tests
  - concourse-integration-tests
- name: final-release
  jobs:
  - major
  - minor
  - patch
  - github-release

resources:
- name: bosh-bootloader-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/bosh-bootloader.git
- name: bosh-bootloader-develop-write
  type: git
  source:
    branch: test-branch
    uri: git@github.com:cloudfoundry/bosh-bootloader.git
    private_key: {{cf_infra_bot_user_github_private_key}}
- name: bosh-bootloader-master
  type: git
  source:
    branch: master
    uri: https://github.com/christianang/bosh-bootloader.git
- name: mega-ci
  type: git
  source:
    branch: test-branch
    uri: https://github.com/cloudfoundry/mega-ci.git
- name: bbl-integration-s3
  type: s3
  source:
    bucket: bbl-integration-tests
    regexp: (.*).tgz
    access_key_id: {{bbl_integration_tests_s3_access_key_id}}
    secret_access_key: {{bbl_integration_tests_s3_secret_access_key}}
- name: version
  type: semver
  source:
    initial_version: 0.0.2
    driver: s3
    bucket: bbl-version
    key: bbl-version
    access_key_id: {{bbl_version_s3_access_key_id}}
    secret_access_key: {{bbl_version_s3_secret_access_key}}
- name: bbl-release
  type: github-release
  source:
    user: cloudfoundry
    repository: bosh-bootloader
    access_token: {{cf_infra_bot_user_github_access_token}}
- name: bbl-compiled-bosh-release-s3
  type: s3
  source:
    bucket: bbl-precompiled-bosh-releases
    regexp: release-bosh-(.*)-on-ubuntu-trusty-stemcell-(.*).tgz
    access_key_id: {{bbl_compiled_bosh_release_s3_access_key_id}}
    secret_access_key: {{bbl_compiled_bosh_release_s3_secret_access_key}}
- name: bosh-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh
- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
- name: bosh-aws-cpi-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/bosh-aws-cpi-release

jobs:
- name: test-bosh-bootloader
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: bosh-bootloader
      resource: bosh-bootloader-develop
      trigger: true
  - task: test
    file: mega-ci/scripts/ci/bosh-bootloader/test.yml

- name: integration-tests
  public: true
  plan:
  - aggregate:
    - get: bosh-bootloader
      resource: bosh-bootloader-develop
      passed: [test-bosh-bootloader]
      trigger: true
    - get: mega-ci
  - task: test
    file: mega-ci/scripts/ci/bosh-bootloader/integration.yml
    config:
      params:
        AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
        AWS_REGION: {{aws_region}}
    on_failure:
      put: bbl-integration-s3
      params:
        file: bbl-integration-s3/*.tgz

- name: concourse-integration-tests
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: bosh-bootloader
      resource: bosh-bootloader-develop
      passed: [integration-tests]
      trigger: true
  - task: test
    file: mega-ci/scripts/ci/bosh-bootloader/concourse_integration.yml
    config:
      params:
        AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
        AWS_REGION: {{aws_region}}
    on_failure:
      put: bbl-integration-s3
      params:
        file: bbl-integration-s3/*.tgz

- name: build-compiled-bosh-release
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: bosh
      resource: bosh-release
      trigger: true
    - get: stemcell
      resource: aws-stemcell
      trigger: true
  - task: build-compiled-bosh-release
    file: mega-ci/scripts/ci/bosh-bootloader/build-compiled-bosh-release/task.yml
    config:
      params:
        BOSH_DIRECTOR: {{mega_bosh_director}}
        BOSH_USER: {{mega_bosh_user}}
        BOSH_PASSWORD: {{mega_bosh_password}}
  - put: bbl-compiled-bosh-release-s3
    params:
      file: bbl-compiled-bosh-release-s3/*.tgz
      acl: public-read

- name: update-release-constants
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: bosh-bootloader
      resource: bosh-bootloader-develop
    - get: stemcell
      resource: aws-stemcell
      passed: [build-compiled-bosh-release]
    - get: bbl-compiled-bosh-release-s3
      trigger: true
      passed: [build-compiled-bosh-release]
    - get: bosh-aws-cpi-release
      trigger: true
  - task: update-release-constants
    file: mega-ci/scripts/ci/bosh-bootloader/update-release-constants/task.yml
  - put: bosh-bootloader-develop-write
    params:
      repository: bosh-bootloader-develop-write
      rebase: true

- name: major
  public: true
  plan:
  - get: version
  - put: version
    params: {bump: major}

- name: minor
  public: true
  plan:
  - get: version
  - put: version
    params: {bump: minor}

- name: patch
  public: true
  plan:
  - get: version
  - put: version
    params: {bump: patch}

- name: github-release
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: bbl-version
      trigger: true
      resource: version
    - get: bosh-bootloader
      resource: bosh-bootloader-master
  - task: build-binaries
    file: mega-ci/scripts/ci/bosh-bootloader/build-final-release/task.yml
  - put: bbl-release
    params:
      name: builds/name
      tag: builds/name
      commitish: builds/commitish
      globs:
      - builds/bin/bbl-*
