groups:
- name: bosh-bootloader
  jobs:
  - test-bosh-bootloader
  - integration-tests
  - concourse-integration-tests
- name: final-release
  jobs:
  - major
  - minor
  - patch
  - github-release

resources:
- name: bosh-bootloader-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/bosh-bootloader.git
- name: bosh-bootloader-master
  type: git
  source:
    branch: master
    uri: https://github.com/christianang/bosh-bootloader.git
- name: mega-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/mega-ci.git
- name: bbl-integration-s3
  type: s3
  source:
    bucket: bbl-integration-tests
    regexp: (.*).tgz
    access_key_id: {{bbl_integration_tests_s3_access_key_id}}
    secret_access_key: {{bbl_integration_tests_s3_secret_access_key}}
- name: version
  type: semver
  source:
    initial_version: 0.0.2
    driver: s3
    bucket: bbl-version
    key: bbl-version
    access_key_id: {{bbl_version_s3_access_key_id}}
    secret_access_key: {{bbl_version_s3_secret_access_key}}
- name: bbl-release
  type: github-release
  source:
    user: cloudfoundry
    repository: bosh-bootloader
    access_token: {{cf_infra_bot_user_access_token}}

jobs:
- name: test-bosh-bootloader
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: bosh-bootloader
      resource: bosh-bootloader-develop
      trigger: true
  - task: test
    file: mega-ci/scripts/ci/bosh-bootloader/test.yml

- name: integration-tests
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: bosh-bootloader
      resource: bosh-bootloader-develop
      passed: [test-bosh-bootloader]
      trigger: true
  - task: test
    file: mega-ci/scripts/ci/bosh-bootloader/integration.yml
    config:
      params:
        AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
        AWS_REGION: {{aws_region}}
    on_failure:
      put: bbl-integration-s3
      params:
        file: bbl-integration-s3/*.tgz

- name: concourse-integration-tests
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: bosh-bootloader
      resource: bosh-bootloader-develop
      passed: [integration-tests]
      trigger: true
  - task: test
    file: mega-ci/scripts/ci/bosh-bootloader/concourse_integration.yml
    config:
      params:
        AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
        AWS_REGION: {{aws_region}}
    on_failure:
      put: bbl-integration-s3
      params:
        file: bbl-integration-s3/*.tgz

- name: major
  public: false
  plan:
  - get: version
  - put: version
    params: {bump: major}

- name: minor
  public: false
  plan:
  - get: version
  - put: version
    params: {bump: minor}

- name: patch
  public: false
  plan:
  - get: version
  - put: version
    params: {bump: patch}

- name: github-release
  public: false
  plan:
  - aggregate:
    - get: mega-ci
    - get: bbl-version
      trigger: true
      resource: version
    - get: bosh-bootloader
      resource: bosh-bootloader-master
  - task: build-binaries
    file: mega-ci/scripts/ci/bosh-bootloader/build-final-release/task.yml
  - put: bbl-release
    params:
      name: builds/name
      tag: builds/name
      commitish: builds/commitish
      globs:
      - builds/bin/bbl-*
