groups:
- name: bosh-bootloader
  jobs:
  - test-bosh-bootloader
  - integration-tests
  - concourse-integration-tests

resources:
- name: bosh-bootloader
  type: git
  source:
    branch: develop
    uri: https://github.com/pivotal-cf-experimental/bosh-bootloader.git
- name: mega-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/mega-ci.git

jobs:
- name: test-bosh-bootloader
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: bosh-bootloader
      trigger: true
  - task: test
    file: mega-ci/scripts/ci/bosh-bootloader/test.yml

- name: integration-tests
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: bosh-bootloader
      passed: [test-bosh-bootloader]
      trigger: true
  - task: test
    file: mega-ci/scripts/ci/bosh-bootloader/integration.yml
    config:
      params:
        AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
        AWS_REGION: {{aws_region}}

- name: concourse-integration-tests
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: bosh-bootloader
      passed: [integration-tests]
      trigger: true
  - task: test
    file: mega-ci/scripts/ci/bosh-bootloader/concourse_integration.yml
    config:
      params:
        AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
        AWS_REGION: {{aws_region}}
