groups:
- name: canaries
  jobs:
    - push-canaries

resources:
- name: mega-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/mega-ci.git
- name: cf-canaries
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/cf_canaries.git
jobs:
- name: push-canaries
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: cf-canaries
  - task: push-canaries
    file: mega-ci/scripts/ci/push-canaries/task.yml
    config:
      params:
        CF_APPS_DOMAIN: {{cf_apps_domain}}
        CF_API_ENDPOINT: {{cf_api_endpoint}}
        CF_API_USER: {{cf_api_user}}
        CF_API_PASSWORD: {{cf_api_password}}
