groups:
- name: consul
  jobs:
  - test-consul
  - deploy-with-cf
  - create-final-release
  - merge-master-into-develop

resources:
- name: mega-ci-env
  type: git
  source:
    branch: master
    private_key: {{mega-ci-env-private-key}}
    uri: git@github.com:cloudfoundry/mega-ci-env.git
- name: mega-ci
  type: git
  source:
    branch: master
    private_key: {{mega-ci-private-key}}
    uri: git@github.com:cloudfoundry/mega-ci.git
- name: consul-release-develop
  type: git
  source:
    branch: develop
    ignore_paths: [.final_builds, releases]
    private_key: {{consul-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/consul-release.git
- name: consul-release-merge-target
  type: git
  source:
    branch: develop
    private_key: {{consul-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/consul-release.git
- name: consul-release-master
  type: git
  source:
    branch: master
    private_key: {{consul-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/consul-release.git
- name: cf-deployment
  type: git
  source:
    branch: master
    private_key: {{cf-deployment-private-key}}
    uri: git@github.com:cloudfoundry/cf-deployment.git

jobs:
- name: test-consul
  public: true
  serial: true
  plan:
  - aggregate:
    - get: private-credentials
      resource: mega-ci-env
    - get: mega-ci
    - get: consul-release
      resource: consul-release-develop
      trigger: true
  - task: run-consats
    file: mega-ci/scripts/ci/run-consats.yml

- name: deploy-with-cf
  public: false
  serial_group: [deploy_consul]
  plan:
  - aggregate:
    - get: private-credentials
      resource: mega-ci-env
    - get: mega-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [test-consul]
      trigger: true
    - get: cf-deployment
  - task: deploy-consul-cf
    file: mega-ci/scripts/ci/deploy-consul-cf/task.yml
    config:
      params:
        STUB_PATH: {{cf_stub_path}}
        STUB_PARTS_PATH: {{cf_stub_parts_path}}
        BOSH_DIRECTOR: {{cf_bosh_director}}
        BOSH_USER: {{cf_bosh_user}}
        BOSH_PASSWORD: {{cf_bosh_password}}
        CF_DEPLOYMENT_TRACE: true

- name: create-final-release
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: private-credentials
      resource: mega-ci-env
    - get: release-repo
      resource: consul-release-develop
      passed: [deploy-with-cf]
      trigger: true
    - get: release-repo-master
      resource: consul-release-master
  - task: create-final-release
    file: mega-ci/scripts/ci/create-final-release.yml
    config:
      params:
        RELEASE_NAME: consul
  - put: consul-release-master
    params:
      repository: create-final-release/release-repo
      tag: create-final-release/release-repo/version_number
      tag_prefix: v

- name: merge-master-into-develop
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: release-repo-master
      resource: consul-release-master
      trigger: true
    - get: release-repo
      resource: consul-release-merge-target
  - task: merge-master-into-develop
    file: mega-ci/scripts/ci/merge-master-into-develop.yml
  - put: consul-release-merge-target
    params:
      repository: merge-master-into-develop/release-repo
