groups:
- name: consul
  jobs:
  - check-git-submodules
  - deploy-bosh-lite-manifests
  - deploy-aws-manifests
  - test-confab
  - test-consul
  - deploy-with-cf
  - deploy-with-diego
  - test-with-cf
  - test-with-diego
  - delete-deployments
  - create-final-release
  - merge-master-into-develop

resources:
- name: mega-ci-env
  type: git
  source:
    branch: master
    private_key: {{mega-ci-env-private-key}}
    uri: git@github.com:cloudfoundry/mega-ci-env.git
- name: consul-cf-env
  type: git
  source:
    branch: master
    private_key: {{consul-cf-env-private-key}}
    uri: git@github.com:cloudfoundry/consul-cf-env.git
- name: oss-s3-buckets-stack
  type: git
  source:
    branch: master
    private_key: {{oss-s3-buckets-stack-private-key}}
    uri: git@github.com:cloudfoundry/oss-s3-buckets-stack.git
- name: mega-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/mega-ci.git
- name: consul-release-develop
  type: git
  source:
    branch: develop
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry-incubator/consul-release.git
- name: consul-release-merge-target
  type: git
  source:
    branch: develop
    private_key: {{consul-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/consul-release.git
- name: consul-release-master
  type: git
  source:
    branch: master
    private_key: {{consul-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/consul-release.git
- name: diego-release-master
  type: git
  source:
    branch: master
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry-incubator/diego-release.git
- name: cf-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment.git
- name: cf-acceptance-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git
- name: bosh-lite
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-lite.git
- name: bosh-lite-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent

jobs:
- name: check-git-submodules
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: repo
      resource: consul-release-develop
      trigger: true
  - task: check-git-submodules
    file: mega-ci/scripts/ci/check-git-submodules/task.yml
    config:
      params:
        PROTOCOL: https

- name: deploy-bosh-lite-manifests
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: bosh-lite
    - get: bosh-lite-stemcell
    - get: release
      resource: consul-release-develop
      passed: [test-consul]
      trigger: true
  - task: deploy-bosh-lite-manifests
    file: mega-ci/scripts/ci/deploy-bosh-lite-manifests.yml
    config:
      params:
        BOSH_AWS_ACCESS_KEY_ID: {{infrastructure_account_aws_access_key_id}}
        BOSH_AWS_SECRET_ACCESS_KEY: {{infrastructure_account_aws_secret_access_key}}
        BOSH_LITE_SECURITY_GROUP: {{bosh_lite_security_group}}
        BOSH_LITE_SUBNET_ID: {{bosh_lite_subnet_id}}
        BOSH_LITE_NAME: bosh-lite-consul
        BOSH_LITE_KEYPAIR: bosh-lite
        BOSH_LITE_PRIVATE_KEY_CONTENTS: {{bosh-lite-private-key}}

- name: deploy-aws-manifests
  public: true
  plan:
  - aggregate:
    - get: private-credentials
      resource: mega-ci-env
    - get: mega-ci
    - get: release
      resource: consul-release-develop
      passed: [test-consul]
      trigger: true
  - task: deploy-aws-manifests
    file: mega-ci/scripts/ci/deploy-aws-manifests/deploy-consul-aws-manifests.yml
    config:
      params:
        BOSH_DIRECTOR: {{cf_bosh_director_url}}
        BOSH_USER: {{cf_bosh_user}}
        BOSH_PASSWORD: {{cf_bosh_password}}
        AWS_ACCESS_KEY_ID: {{mega_ci_account_aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{mega_ci_account_aws_secret_access_key}}
        AWS_DEFAULT_REGION: {{mega_ci_account_aws_default_region}}
        MANIFEST_PATH: manifests/aws/multi-az-ssl.yml

- name: test-confab
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [check-git-submodules]
      trigger: true
  - task: test-confab
    file: mega-ci/scripts/ci/confab/test.yml

- name: test-consul
  public: true
  serial: true
  plan:
  - aggregate:
    - get: private-credentials
      resource: mega-ci-env
    - get: mega-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [test-confab]
      trigger: true
  - task: run-consats
    file: mega-ci/scripts/ci/run-consats/task.yml
    config:
      params:
        AWS_ACCESS_KEY_ID: {{mega_ci_account_aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{mega_ci_account_aws_secret_access_key}}
        AWS_REGION: {{mega_ci_account_aws_default_region}}
        AWS_AVAILIBILITY_ZONE: {{mega_ci_account_aws_availability_zone}}
        AWS_SECURITY_GROUP_NAME: {{mega_ci_account_aws_security_group_name}}
        AWS_SUBNET_ID: {{mega_ci_account_aws_subnet_id}}
        BOSH_TARGET: {{bosh_target}}
        BOSH_DIRECTOR_UUID: {{bosh_director_uuid}}
        BOSH_USERNAME: {{bosh_username}}
        BOSH_PASSWORD: {{bosh_password}}
        BOSH_DIRECTOR_CA_CERT: {{bosh_director_ca_cert}}
        REGISTRY_USERNAME: {{registry_username}}
        REGISTRY_PASSWORD: {{registry_password}}

- name: deploy-with-cf
  public: false
  serial_group: [cf, diego]
  plan:
  - aggregate:
    - get: consul-cf-env
    - get: mega-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [test-consul]
      trigger: true
    - get: cf-deployment
  - task: deploy-consul-cf
    file: mega-ci/scripts/ci/deploy-consul-cf/task.yml
    config:
      params:
        BOSH_DIRECTOR: {{consul_cf_bosh_director}}
        BOSH_USER: {{consul_cf_bosh_user}}
        BOSH_PASSWORD: {{consul_cf_bosh_password}}
        CF_DEPLOYMENT_TRACE: true

- name: deploy-with-diego
  public: false
  serial_group: [cf, diego]
  plan:
  - aggregate:
    - get: consul-cf-env
    - get: mega-ci
    - get: diego-release
      resource: diego-release-master
    - get: consul-release
      resource: consul-release-develop
      passed: [deploy-with-cf]
      trigger: true
  - task: deploy-consul-diego
    file: mega-ci/scripts/ci/deploy-consul-diego/task.yml
    config:
      params:
        BOSH_DIRECTOR: {{consul_cf_bosh_director}}
        BOSH_USER: {{consul_cf_bosh_user}}
        BOSH_PASSWORD: {{consul_cf_bosh_password}}

- name: test-with-cf
  public: false
  serial_group: [cf]
  plan:
  - aggregate:
    - get: mega-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [deploy-with-diego]
      trigger: true
  - task: run-cats
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        BOSH_DIRECTOR: {{cf_bosh_director_url}}
        BOSH_USER: {{cf_bosh_user}}
        BOSH_PASSWORD: {{cf_bosh_password}}
        DEPLOYMENT_NAME: consul-cf-deployment
        COMMAND: run errand acceptance_tests

- name: test-with-diego
  public: false
  serial_group: [diego]
  plan:
  - aggregate:
    - get: mega-ci
    - get: cf-acceptance-tests
    - get: consul-release
      resource: consul-release-develop
      passed: [deploy-with-diego]
      trigger: true
  - task: run-cats
    file: mega-ci/scripts/ci/test-diego/task.yml
    config:
      params:
        CF_DOMAIN: {{consul_cf_domain}}
        CF_USER: {{consul_cf_user}}
        CF_PASSWORD: {{consul_cf_password}}

- name: delete-deployments
  public: false
  serial_group: [cf, diego]
  plan:
  - aggregate:
    - get: private-credentials
      resource: mega-ci-env
    - get: mega-ci
    - get: consul-release
      resource: consul-release-develop
      passed:
      - test-with-cf
      - test-with-diego
      trigger: true
    - task: delete-diego-deployment
      file: mega-ci/scripts/ci/run-bosh-command.yml
      config:
        params:
          DEPLOYMENT_NAME: consul-diego-deployment-diego
          COMMAND: delete deployment consul-cf-deployment-diego
          BOSH_DIRECTOR: {{consul_cf_bosh_director}}
          BOSH_USER: {{consul_cf_bosh_user}}
          BOSH_PASSWORD: {{consul_cf_bosh_password}}
    - task: delete-cf-deployment
      file: mega-ci/scripts/ci/run-bosh-command.yml
      config:
        params:
          DEPLOYMENT_NAME: consul-cf-deployment
          COMMAND: delete deployment consul-cf-deployment
          BOSH_DIRECTOR: {{consul_cf_bosh_director}}
          BOSH_USER: {{consul_cf_bosh_user}}
          BOSH_PASSWORD: {{consul_cf_bosh_password}}

- name: create-final-release
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: oss-s3-buckets-stack
      resource: oss-s3-buckets-stack
    - get: release-repo
      resource: consul-release-develop
      passed: [delete-deployments]
      trigger: true
    - get: release-repo-master
      resource: consul-release-master
  - task: create-final-release
    file: mega-ci/scripts/ci/create-final-release/task.yml
    config:
      params:
        RELEASE_NAME: consul
  - put: consul-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v

- name: merge-master-into-develop
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: release-repo-master
      resource: consul-release-master
      trigger: true
    - get: release-repo
      resource: consul-release-merge-target
  - task: merge-master-into-develop
    file: mega-ci/scripts/ci/merge-master-into-develop/task.yml
  - put: consul-release-merge-target
    params:
      repository: final-release-repo
