groups:
- name: consul
  jobs:
  - deploy-bosh-lite-manifests
  - test-consul
  - deploy-with-cf
  - test-with-cf
  - create-final-release
  - merge-master-into-develop

resources:
- name: mega-ci-env
  type: git
  source:
    branch: master
    private_key: {{mega-ci-env-private-key}}
    uri: git@github.com:cloudfoundry/mega-ci-env.git
- name: mega-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/mega-ci.git
- name: consul-release-develop
  type: git
  source:
    branch: develop
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry-incubator/consul-release.git
- name: consul-release-merge-target
  type: git
  source:
    branch: develop
    private_key: {{consul-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/consul-release.git
- name: consul-release-master
  type: git
  source:
    branch: master
    private_key: {{consul-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/consul-release.git
- name: cf-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment.git
- name: consul-release-manifests
  type: git
  source:
    branch: develop
    paths: [manifests/bosh-lite, jobs]
    uri: https://github.com/cloudfoundry-incubator/consul-release.git
- name: bosh-lite
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-lite.git

jobs:
- name: deploy-bosh-lite-manifests
  public: true
  plan:
  - aggregate:
    - get: private-credentials
      resource: mega-ci-env
    - get: mega-ci
    - get: bosh-lite
    - get: release
      resource: consul-release-manifests
      trigger: true
  - task: deploy-bosh-lite-manifests
    file: mega-ci/scripts/ci/deploy-bosh-lite-manifests.yml
    config:
      params:
        BOSH_AWS_ACCESS_KEY_ID: {{bosh_aws_access_key_id}}
        BOSH_AWS_SECRET_ACCESS_KEY: {{bosh_aws_secret_access_key}}
        BOSH_LITE_SECURITY_GROUP: {{bosh_lite_security_group}}
        BOSH_LITE_SUBNET_ID: {{bosh_lite_subnet_id}}
        BOSH_LITE_NAME: bosh-lite

- name: test-consul
  public: true
  serial: true
  plan:
  - aggregate:
    - get: private-credentials
      resource: mega-ci-env
    - get: mega-ci
    - get: consul-release
      resource: consul-release-develop
      trigger: true
  - task: run-consats
    file: mega-ci/scripts/ci/run-consats.yml

- name: deploy-with-cf
  public: false
  serial_group: [deploy_consul]
  plan:
  - aggregate:
    - get: private-credentials
      resource: mega-ci-env
    - get: mega-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [test-consul]
      trigger: true
    - get: cf-deployment
  - task: deploy-consul-cf
    file: mega-ci/scripts/ci/deploy-consul-cf/task.yml
    config:
      params:
        STUB_PATH: {{cf_stub_path}}
        STUB_PARTS_PATH: {{cf_stub_parts_path}}
        BOSH_DIRECTOR: {{cf_bosh_director}}
        BOSH_USER: {{cf_bosh_user}}
        BOSH_PASSWORD: {{cf_bosh_password}}
        CF_DEPLOYMENT_TRACE: true

- name: test-with-cf
  public: false
  serial_group: [deploy_consul]
  plan:
  - aggregate:
    - get: private-credentials
      resource: mega-ci-env
    - get: mega-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [deploy-with-cf]
      trigger: true
  - task: run-cats
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        ENVIRONMENT: mega-ci
        DEPLOYMENT_NAME: consul-cf-deployment
        COMMAND: run errand acceptance_tests
    on_success:
      task: delete-deployment
      file: mega-ci/scripts/ci/run-bosh-command.yml
      config:
        params:
          ENVIRONMENT: mega-ci
          DEPLOYMENT_NAME: consul-cf-deployment
          COMMAND: delete deployment consul-cf-deployment

- name: create-final-release
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: private-credentials
      resource: mega-ci-env
    - get: release-repo
      resource: consul-release-develop
      passed: [test-with-cf]
      trigger: true
    - get: release-repo-master
      resource: consul-release-master
  - task: create-final-release
    file: mega-ci/scripts/ci/create-final-release.yml
    config:
      params:
        RELEASE_NAME: consul
  - put: consul-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v

- name: merge-master-into-develop
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: release-repo-master
      resource: consul-release-master
      trigger: true
    - get: release-repo
      resource: consul-release-merge-target
  - task: merge-master-into-develop
    file: mega-ci/scripts/ci/merge-master-into-develop/task.yml
  - put: consul-release-merge-target
    params:
      repository: final-release-repo
