groups:
- name: destiny
  jobs:
  - test-destiny

resources:
- name: destiny
  type: git
  source:
    branch: master
    uri: https://github.com/pivotal-cf-experimental/destiny.git
- name: mega-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/mega-ci.git

jobs:
- name: test-destiny
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: destiny
      trigger: true
  - task: test
    file: mega-ci/scripts/ci/destiny/test.yml
