groups:
- name: etcd
  jobs:
  - check-git-submodules
  - test-etcd
  - create-final-release
  - merge-master-into-develop
  - deploy-bosh-lite-manifests
  - deploy-aws-manifests
  - deploy-with-cf
  - test-with-cf

resources:
- name: mega-ci-env
  type: git
  source:
    branch: master
    private_key: {{mega-ci-env-private-key}}
    uri: git@github.com:cloudfoundry/mega-ci-env.git
- name: mega-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/mega-ci.git
- name: etcd-release-develop
  type: git
  source:
    branch: develop
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry-incubator/etcd-release.git
- name: etcd-release-merge-target
  type: git
  source:
    branch: develop
    private_key: {{etcd-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/etcd-release.git
- name: etcd-release-master
  type: git
  source:
    branch: master
    private_key: {{etcd-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/etcd-release.git
- name: consul-release-develop
  type: git
  source:
    branch: develop
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry-incubator/consul-release.git
- name: cf-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment.git
- name: bosh-lite
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-lite.git

jobs:
- name: check-git-submodules
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: repo
      resource: etcd-release-develop
      trigger: true
  - task: check-git-submodules
    file: mega-ci/scripts/ci/check-git-submodules/task.yml
    config:
      params:
        PROTOCOL: https

- name: deploy-bosh-lite-manifests
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: bosh-lite
    - get: release
      resource: etcd-release-develop
      passed: [test-etcd]
      trigger: true
  - task: deploy-bosh-lite-manifests
    file: mega-ci/scripts/ci/deploy-bosh-lite-manifests.yml
    config:
      params:
        BOSH_AWS_ACCESS_KEY_ID: {{bosh_aws_access_key_id}}
        BOSH_AWS_SECRET_ACCESS_KEY: {{bosh_aws_secret_access_key}}
        BOSH_LITE_SECURITY_GROUP: {{bosh_lite_security_group}}
        BOSH_LITE_SUBNET_ID: {{bosh_lite_subnet_id}}
        BOSH_LITE_NAME: bosh-lite-etcd
        BOSH_LITE_KEYPAIR: bosh-lite-etcd
        BOSH_LITE_PRIVATE_KEY_CONTENTS: {{bosh-lite-private-key}}

- name: deploy-aws-manifests
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: consul-release
      resource: consul-release-develop
    - get: release
      resource: etcd-release-develop
      passed: [test-etcd]
      trigger: true
  - task: deploy-aws-manifests
    file: mega-ci/scripts/ci/deploy-aws-manifests/deploy-etcd-aws-manifests.yml
    config:
      params:
        BOSH_DIRECTOR: {{cf_bosh_director_url}}
        BOSH_USER: {{cf_bosh_user}}
        BOSH_PASSWORD: {{cf_bosh_password}}
        AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
        AWS_DEFAULT_REGION: {{aws_region}}

- name: test-etcd
  public: true
  serial: true
  plan:
  - aggregate:
    - get: private-credentials
      resource: mega-ci-env
    - get: mega-ci
    - get: etcd-release
      trigger: true
      resource: etcd-release-develop
  - task: run-eats
    file: mega-ci/scripts/ci/run-eats.yml
    config:
      params:
        BOSH_TARGET: {{cf_bosh_director}}
        BOSH_USERNAME: {{cf_bosh_user}}
        BOSH_PASSWORD: {{cf_bosh_password}}
        BOSH_DIRECTOR_CA_CERT: {{bosh_director_ca_cert}}
        AWS_SUBNET: {{aws_subnet}}
        AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
        AWS_DEFAULT_KEY_NAME: {{aws_default_key_name}}
        AWS_DEFAULT_SECURITY_GROUPS: {{aws_default_security_groups}}
        AWS_REGION: {{aws_region}}
        REGISTRY_HOST: {{registry_host}}
        REGISTRY_PORT: {{registry_port}}
        REGISTRY_USERNAME: {{registry_username}}
        REGISTRY_PASSWORD: {{registry_password}}

- name: deploy-with-cf
  public: false
  serial_group: [deploy_etcd]
  plan:
  - aggregate:
    - get: private-credentials
      resource: mega-ci-env
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      passed: [test-etcd]
      trigger: true
    - get: cf-deployment
  - task: deploy-etcd-cf
    file: mega-ci/scripts/ci/deploy-etcd-cf/task.yml
    config:
      params:
        STUB_PATH: {{cf_stub_path}}
        STUB_PARTS_PATH: {{cf_stub_parts_path}}
        BOSH_DIRECTOR: {{cf_bosh_director}}
        BOSH_USER: {{cf_bosh_user}}
        BOSH_PASSWORD: {{cf_bosh_password}}
        CF_DEPLOYMENT_TRACE: true

- name: test-with-cf
  public: false
  serial_group: [deploy_etcd]
  plan:
  - aggregate:
    - get: private-credentials
      resource: mega-ci-env
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      passed: [deploy-with-cf]
      trigger: true
  - task: run-cats
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        ENVIRONMENT: mega-ci
        DEPLOYMENT_NAME: etcd-cf-deployment
        COMMAND: run errand acceptance_tests
    on_success:
      task: delete-deployment
      file: mega-ci/scripts/ci/run-bosh-command.yml
      config:
        params:
          ENVIRONMENT: mega-ci
          DEPLOYMENT_NAME: etcd-cf-deployment
          COMMAND: delete deployment etcd-cf-deployment

- name: create-final-release
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: private-credentials
      resource: mega-ci-env
    - get: release-repo
      resource: etcd-release-develop
      passed: [test-with-cf]
      trigger: true
    - get: release-repo-master
      resource: etcd-release-master
  - task: create-final-release
    file: mega-ci/scripts/ci/create-final-release/task.yml
    config:
      params:
        RELEASE_NAME: etcd
  - put: etcd-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v


- name: merge-master-into-develop
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: release-repo-master
      resource: etcd-release-master
      trigger: true
    - get: release-repo
      resource: etcd-release-merge-target
  - task: merge-master-into-develop
    file: mega-ci/scripts/ci/merge-master-into-develop/task.yml
  - put: etcd-release-merge-target
    params:
      repository: final-release-repo
