groups:
- name: etcd
  jobs:
  - test-etcd
  - clean-deployment

resources:
- name: deployments-runtime
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/deployments-runtime.git
- name: mega-ci
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/mega-ci.git
- name: etcd-release
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry-incubator/etcd-release.git

jobs:
- name: test-etcd
  plan:
  - aggregate:
    - get: deployments-runtime
    - get: mega-ci
    - get: etcd-release
      trigger: true
  - aggregate:
    - task: generate-iaas-settings-etcd
      file: mega-ci/scripts/ci/generate-iaas-settings.yml
      config:
        params:
          DEPLOYMENT_DIR: mega-ci
          DEPLOYMENT: etcd
          SUBNET: EtcdSubnet
          SECURITY_GROUP: EtcdSecurityGroup
          STACK_NAME: concourse
    - task: generate-iaas-settings-turbulence
      file: mega-ci/scripts/ci/generate-iaas-settings.yml
      config:
        params:
          DEPLOYMENT_DIR: mega-ci
          DEPLOYMENT: turbulence
          SUBNET: EtcdSubnet
          SECURITY_GROUP: EtcdSecurityGroup
          STACK_NAME: concourse
  - task: run-eats
    file: mega-ci/scripts/ci/run-eats.yml
    config:
      params:
        CPI_RELEASE_NAME: bosh-warden-cpi
        CPI_RELEASE_URL: http://bosh.io/d/github.com/cppforlife/bosh-warden-cpi-release?v=21
        IAAS_SETTINGS_TURBULENCE: generate-iaas-settings-turbulence/generated-stubs/iaas-settings.yml
        IAAS_SETTINGS_ETCD: generate-iaas-settings-etcd/generated-stubs/iaas-settings.yml
        BOSH_OPERATION_TIMEOUT: 20m

- name: clean-deployment
  plan:
  - aggregate:
    - get: deployments-runtime
      passed: [test-etcd]
      trigger: false
    - get: mega-ci
  - task: clean
    privileged: true
    file: mega-ci/scripts/ci/clean-deployment.yml
