groups:
- name: etcd
  jobs:
  - test-etcd
  - clean-deployment
  - create-final-release
  - merge-master-into-develop
  - deploy-and-test-with-cf

resources:
- name: deployments-runtime
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/deployments-runtime.git
- name: runtime-credentials
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/runtime-credentials.git
- name: mega-ci
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/mega-ci.git
- name: etcd-release-develop
  type: git
  source:
    branch: develop
    ignore_paths: [.final_builds, releases]
    fetch: [master]
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry-incubator/etcd-release.git
- name: etcd-release-merge-target
  type: git
  source:
    branch: develop
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry-incubator/etcd-release.git
- name: etcd-release-master
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry-incubator/etcd-release.git
- name: consul-release
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry-incubator/consul-release.git
- name: cf-release
  type: git
  source:
    branch: develop
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/cf-release.git
- name: cf-deployment
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/cf-deployment.git
- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

jobs:
- name: test-etcd
  public: true
  serial: true
  plan:
  - aggregate:
    - get: deployments-runtime
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      trigger: true
  - aggregate:
    - task: generate-iaas-settings-etcd
      file: mega-ci/scripts/ci/generate-iaas-settings.yml
      config:
        params:
          DEPLOYMENT_DIR: mega-ci
          DEPLOYMENT: etcd
          SUBNET: EtcdSubnet
          SECURITY_GROUP: EtcdSecurityGroup
          STACK_NAME: concourse
    - task: generate-iaas-settings-turbulence
      file: mega-ci/scripts/ci/generate-iaas-settings.yml
      config:
        params:
          DEPLOYMENT_DIR: mega-ci
          DEPLOYMENT: turbulence
          SUBNET: EtcdSubnet
          SECURITY_GROUP: EtcdSecurityGroup
          STACK_NAME: concourse
    - task: generate-property-overrides-turbulence
      file: mega-ci/scripts/ci/generate-property-overrides-turbulence.yml
      config:
        params:
          DEPLOYMENT_DIR: mega-ci
  - task: run-eats
    file: mega-ci/scripts/ci/run-eats.yml
    config:
      params:
        CPI_RELEASE_NAME: bosh-aws-cpi
        CPI_RELEASE_URL: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=30
        IAAS_SETTINGS_TURBULENCE: generate-iaas-settings-turbulence/generated-stubs/iaas-settings.yml
        IAAS_SETTINGS_ETCD: generate-iaas-settings-etcd/generated-stubs/iaas-settings.yml
        PROPERTY_OVERRIDES_TURBULENCE: generate-property-overrides-turbulence/generated-stubs/property-overrides-turbulence.yml
        BOSH_OPERATION_TIMEOUT: 20m

- name: clean-deployment
  public: true
  serial: true
  plan:
  - aggregate:
    - get: deployments-runtime
    - get: mega-ci
    - get: etcd-release-develop
      trigger: true
      passed: [test-etcd]
  - task: clean
    file: mega-ci/scripts/ci/clean-deployment.yml

- name: deploy-and-test-with-cf
  public: false
  serial: true
  plan:
  - aggregate:
    - get: deployments-runtime
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      passed: [test-etcd]
      trigger: true
    - get: cf-release
    - get: cf-deployment
    - get: stemcell
      resource: aws-stemcell
    - get: consul-release
  - task: deploy-etcd-cf
    file: mega-ci/scripts/ci/deploy-etcd-cf.yml
    config:
      params:
        STUB_PATH: {{cf_stub_path}}
        STUB_PARTS_PATH: {{cf_stub_parts_path}}
  - task: run-cats
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        ENVIRONMENT: mega-ci
        DEPLOYMENT_NAME: etcd-cf-deployment
        COMMAND: run errand acceptance_tests
    on_success:
      task: delete-deployment
      file: mega-ci/scripts/ci/run-bosh-command.yml
      config:
        params:
          ENVIRONMENT: mega-ci
          DEPLOYMENT_NAME: etcd-cf-deployment
          COMMAND: delete deployment etcd-cf-deployment

- name: create-final-release
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: deployments-runtime
    - get: release-repo
      resource: etcd-release-develop
      passed: [deploy-and-test-with-cf]
      trigger: true
  - task: create-final-release
    file: mega-ci/scripts/ci/create-final-release.yml
    config:
      params:
        RELEASE_NAME: etcd
  - put: etcd-release-master
    params:
      repository: create-final-release/release-repo
      tag: create-final-release/release-repo/version_number


- name: merge-master-into-develop
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: etcd-release-master
      trigger: true
    - get: release-repo
      resource: etcd-release-merge-target
  - task: merge-master-into-develop
    file: mega-ci/scripts/ci/merge-master-into-develop.yml
  - put: etcd-release-merge-target
    params:
      repository: merge-master-into-develop/release-repo
