groups:
- name: etcd
  jobs:
  - check-git-submodules
  - test-etcd-metrics-server
  - test-etcd
  - deploy-bosh-lite-manifests
  - deploy-aws-manifests
  - deploy-with-cf
  - deploy-with-diego
  - test-with-diego
  - test-cf-tls-upgrade
  - delete-deployments
  - create-final-release
  - merge-master-into-develop

resources:
- name: mega-ci-env
  type: git
  source:
    branch: master
    private_key: {{mega-ci-env-private-key}}
    uri: git@github.com:cloudfoundry/mega-ci-env.git
- name: etcd-cf-env
  type: git
  source:
    branch: master
    private_key: {{etcd-cf-env-private-key}}
    uri: git@github.com:cloudfoundry/etcd-cf-env.git
- name: oss-s3-buckets-stack
  type: git
  source:
    branch: master
    private_key: {{oss-s3-buckets-stack-private-key}}
    uri: git@github.com:cloudfoundry/oss-s3-buckets-stack.git
- name: mega-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/mega-ci.git
- name: etcd-release-develop
  type: git
  source:
    branch: develop
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry-incubator/etcd-release.git
- name: etcd-release-merge-target
  type: git
  source:
    branch: develop
    private_key: {{etcd-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/etcd-release.git
- name: etcd-release-master
  type: git
  source:
    branch: master
    private_key: {{etcd-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/etcd-release.git
- name: consul-release-master
  type: git
  source:
    branch: master
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry-incubator/consul-release.git
- name: diego-release-master
  type: git
  source:
    branch: master
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry/diego-release.git
- name: cf-release
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/cf-release.git
- name: bosh-lite
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-lite.git
- name: bosh-lite-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent

jobs:
- name: check-git-submodules
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: repo
      resource: etcd-release-develop
      trigger: true
  - task: check-git-submodules
    file: mega-ci/scripts/ci/check-git-submodules/task.yml
    config:
      params:
        PROTOCOL: https

- name: deploy-bosh-lite-manifests
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: bosh-lite
    - get: bosh-lite-stemcell
    - get: release
      resource: etcd-release-develop
      passed: [test-etcd]
      trigger: true
  - task: deploy-bosh-lite-manifests
    file: mega-ci/scripts/ci/deploy-bosh-lite-manifests.yml
    config:
      params:
        BOSH_AWS_ACCESS_KEY_ID: {{infrastructure_account_aws_access_key_id}}
        BOSH_AWS_SECRET_ACCESS_KEY: {{infrastructure_account_aws_secret_access_key}}
        BOSH_LITE_SECURITY_GROUP: {{bosh_lite_security_group}}
        BOSH_LITE_SUBNET_ID: {{bosh_lite_subnet_id}}
        BOSH_LITE_NAME: bosh-lite-etcd
        BOSH_LITE_KEYPAIR: bosh-lite-etcd
        BOSH_LITE_PRIVATE_KEY_CONTENTS: {{bosh-lite-private-key}}
        MANIFESTS: "manifests/bosh-lite/3-node-with-ssl.yml manifests/bosh-lite/3-node-no-ssl.yml"
        DEPENDENCIES: "cloudfoundry-incubator/consul-release"

- name: deploy-aws-manifests
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: consul-release
      resource: consul-release-master
    - get: release
      resource: etcd-release-develop
      passed: [test-etcd]
      trigger: true
  - task: deploy-multi-az-no-ssl-manifest
    file: mega-ci/scripts/ci/deploy-aws-manifests/deploy-etcd-aws-manifests.yml
    config:
      params:
        BOSH_DIRECTOR: {{cf_bosh_director_url}}
        BOSH_USER: {{cf_bosh_user}}
        BOSH_PASSWORD: {{cf_bosh_password}}
        AWS_ACCESS_KEY_ID: {{mega_ci_account_aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{mega_ci_account_aws_secret_access_key}}
        AWS_DEFAULT_REGION: {{mega_ci_account_aws_region}}
        MANIFEST_PATH: manifests/aws/multi-az-no-ssl.yml
  - task: deploy-multi-az-ssl-manifest
    file: mega-ci/scripts/ci/deploy-aws-manifests/deploy-etcd-aws-manifests.yml
    config:
      params:
        BOSH_DIRECTOR: {{cf_bosh_director_url}}
        BOSH_USER: {{cf_bosh_user}}
        BOSH_PASSWORD: {{cf_bosh_password}}
        AWS_ACCESS_KEY_ID: {{mega_ci_account_aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{mega_ci_account_aws_secret_access_key}}
        AWS_DEFAULT_REGION: {{mega_ci_account_aws_region}}
        MANIFEST_PATH: manifests/aws/multi-az-ssl.yml

- name: test-etcd-metrics-server
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      passed: [check-git-submodules]
      trigger: true
  - task: test-etcd-metrics-server
    file: mega-ci/scripts/ci/test-etcd-metrics-server/test.yml

- name: test-etcd
  public: true
  serial: true
  plan:
  - aggregate:
    - get: private-credentials
      resource: mega-ci-env
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      passed: [test-etcd-metrics-server]
      trigger: true
  - task: run-eats
    file: mega-ci/scripts/ci/run-eats.yml
    config:
      params:
        BOSH_TARGET: {{cf_bosh_director}}
        BOSH_USERNAME: {{cf_bosh_user}}
        BOSH_PASSWORD: {{cf_bosh_password}}
        BOSH_DIRECTOR_CA_CERT: {{bosh_director_ca_cert}}
        AWS_SUBNET: {{mega_ci_account_aws_subnet}}
        AWS_ACCESS_KEY_ID: {{mega_ci_account_aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{mega_ci_account_aws_secret_access_key}}
        AWS_DEFAULT_KEY_NAME: {{mega_ci_account_aws_default_key_name}}
        AWS_DEFAULT_SECURITY_GROUPS: {{mega_ci_account_aws_default_security_groups}}
        AWS_REGION: {{mega_ci_account_aws_region}}
        REGISTRY_HOST: {{registry_host}}
        REGISTRY_PORT: {{registry_port}}
        REGISTRY_USERNAME: {{registry_username}}
        REGISTRY_PASSWORD: {{registry_password}}

- name: deploy-with-cf
  public: true
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: etcd-cf-env
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      passed: [test-etcd]
      trigger: true
    - get: cf-release
  - task: deploy-etcd-cf
    file: mega-ci/scripts/ci/deploy-etcd-cf/task.yml
    config:
      params:
        BOSH_DIRECTOR: {{etcd_cf_bosh_director}}
        BOSH_USER: {{etcd_cf_bosh_user}}
        BOSH_PASSWORD: {{etcd_cf_bosh_password}}
        CF_DEPLOYMENT_TRACE: true

- name: deploy-with-diego
  public: true
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: etcd-cf-env
    - get: mega-ci
    - get: diego-release
      resource: diego-release-master
    - get: etcd-release
      resource: etcd-release-develop
      passed: [deploy-with-cf]
      trigger: true
  - task: deploy-etcd-diego
    file: mega-ci/scripts/ci/deploy-etcd-diego/task.yml
    config:
      params:
        BOSH_DIRECTOR: {{etcd_cf_bosh_director}}
        BOSH_USER: {{etcd_cf_bosh_user}}
        BOSH_PASSWORD: {{etcd_cf_bosh_password}}

- name: test-with-diego
  public: true
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      passed: [deploy-with-diego]
      trigger: true
  - task: run-cats
    file: mega-ci/scripts/ci/test-diego/task.yml
    config:
      params:
        CF_DOMAIN: {{etcd_cf_domain}}
        CF_USER: {{etcd_cf_user}}
        CF_PASSWORD: {{etcd_cf_password}}
        BOSH_DIRECTOR: {{etcd_cf_bosh_director}}
        BOSH_USER: {{etcd_cf_bosh_user}}
        BOSH_PASSWORD: {{etcd_cf_bosh_password}}
        DEPLOYMENT_NAME: etcd-cf-deployment

- name: test-cf-tls-upgrade
  serial_group: [cf]
  plan:
  - aggregate:
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      passed: [test-with-diego]
      trigger: true
  - task: run-cf-tls-upgrade-test
    file: mega-ci/scripts/ci/test-cf-tls-upgrade/task.yml
    config:
      params:
        CF_DOMAIN: {{etcd_cf_domain}}
        CF_USER: {{etcd_cf_user}}
        CF_PASSWORD: {{etcd_cf_password}}
        BOSH_DIRECTOR: {{etcd_cf_bosh_director}}
        BOSH_USER: {{etcd_cf_bosh_user}}
        BOSH_PASSWORD: {{etcd_cf_bosh_password}}
        DEPLOYMENT_NAME: etcd-cf-deployment

- name: delete-deployments
  public: true
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      passed:
      - test-cf-tls-upgrade
      trigger: true
  - task: delete-diego-deployment
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        DEPLOYMENT_NAME: etcd-cf-deployment-diego
        COMMAND: delete deployment etcd-cf-deployment-diego
        BOSH_DIRECTOR: {{etcd_cf_bosh_director}}
        BOSH_USER: {{etcd_cf_bosh_user}}
        BOSH_PASSWORD: {{etcd_cf_bosh_password}}
  - task: delete-cf-deployment
    file: mega-ci/scripts/ci/run-bosh-command.yml
    config:
      params:
        DEPLOYMENT_NAME: etcd-cf-deployment
        COMMAND: delete deployment etcd-cf-deployment
        BOSH_DIRECTOR: {{etcd_cf_bosh_director}}
        BOSH_USER: {{etcd_cf_bosh_user}}
        BOSH_PASSWORD: {{etcd_cf_bosh_password}}
  - task: cleanup-releases
    file: mega-ci/scripts/ci/run-bosh-cleanup.yml
    config:
      params:
        BOSH_DIRECTOR: {{etcd_cf_bosh_director}}
        BOSH_USER: {{etcd_cf_bosh_user}}
        BOSH_PASSWORD: {{etcd_cf_bosh_password}}

- name: create-final-release
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: oss-s3-buckets-stack
      resource: oss-s3-buckets-stack
    - get: release-repo
      resource: etcd-release-develop
      passed: [delete-deployments]
      trigger: true
    - get: release-repo-master
      resource: etcd-release-master
  - task: create-final-release
    file: mega-ci/scripts/ci/create-final-release/task.yml
    config:
      params:
        RELEASE_NAME: etcd
  - put: etcd-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v


- name: merge-master-into-develop
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: release-repo-master
      resource: etcd-release-master
      trigger: true
    - get: release-repo
      resource: etcd-release-merge-target
  - task: merge-master-into-develop
    file: mega-ci/scripts/ci/merge-master-into-develop/task.yml
  - put: etcd-release-merge-target
    params:
      repository: final-release-repo
