groups:
- name: etcd
  jobs:
  - check-git-submodules
  - test-etcd-proxy
  - test-etcd-metrics-server
  - compile-etcd-develop
  - test-etcd
  - test-etcd-turbulence
  - deploy-bosh-lite-manifests
  - deploy-aws-manifests
  - deploy-with-cf
  - deploy-with-diego
  - test-with-diego
  - test-cf-tls-upgrade
  - delete-deployments
  - create-final-release
  - merge-master-into-develop
- name: cleanup
  jobs:
  - delete-etcd-deployments
- name: compile-dependencies
  jobs:
  - compile-consul-release

resources:
- name: etcd-cf-env
  type: git
  source:
    branch: master
    private_key: {{etcd-cf-env-private-key}}
    uri: git@github.com:cloudfoundry/etcd-cf-env.git
- name: oss-s3-buckets-stack
  type: git
  source:
    branch: master
    private_key: {{oss-s3-buckets-stack-private-key}}
    uri: git@github.com:cloudfoundry/oss-s3-buckets-stack.git
- name: mega-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/mega-ci.git
- name: etcd-release-develop
  type: git
  source:
    branch: develop
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry-incubator/etcd-release.git
- name: etcd-release-merge-target
  type: git
  source:
    branch: develop
    private_key: {{etcd-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/etcd-release.git
- name: etcd-release-master
  type: git
  source:
    branch: master
    private_key: {{etcd-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/etcd-release.git
- name: consul-release-master
  type: git
  source:
    branch: master
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry-incubator/consul-release.git
- name: diego-release-master
  type: git
  source:
    branch: master
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry/diego-release.git
- name: cf-release
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/cf-release.git
- name: bosh-lite
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-lite.git
- name: bosh-lite-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
- name: turbulence-release
  type: bosh-io-release
  source:
    repository: cppforlife/turbulence-release
- name: bosh-aws-cpi-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/bosh-aws-cpi-release
- name: consul-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/consul-release
- name: compiled-consul-release
  type: s3
  source:
    bucket: etcd-compiled-releases
    regexp: compiled-consul-releases/release-consul-(.*)-on-ubuntu-trusty-stemcell-(.*).tgz
    access_key_id: {{etcd_compiled_bosh_release_s3_access_key_id}}
    secret_access_key: {{etcd_compiled_bosh_release_s3_secret_access_key}}
- name: compiled-etcd-release
  type: s3
  source:
    bucket: etcd-compiled-releases
    regexp: compiled-etcd-releases/release-etcd-9999+dev.(.*)-on-ubuntu-trusty-stemcell-(.*).tgz
    access_key_id: {{etcd_compiled_bosh_release_s3_access_key_id}}
    secret_access_key: {{etcd_compiled_bosh_release_s3_secret_access_key}}
jobs:
- name: delete-etcd-deployments
  public: false
  plan:
  - aggregate:
    - get: mega-ci
  - task: delete-deployments
    file: mega-ci/scripts/ci/delete-deployments/task.yml
    config:
      params:
        BOSH_DIRECTOR: {{cf_bosh_director}}
        BOSH_USER: {{cf_bosh_user}}
        BOSH_PASSWORD: {{cf_bosh_password}}
        DEPLOYMENTS_WITH_WORD: etcd

- name: check-git-submodules
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: repo
      resource: etcd-release-develop
      trigger: true
  - task: check-git-submodules
    file: mega-ci/scripts/ci/check-git-submodules/task.yml
    config:
      params:
        PROTOCOL: https

- name: deploy-bosh-lite-manifests
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: bosh-lite
    - get: bosh-lite-stemcell
    - get: release
      resource: etcd-release-develop
      passed: [test-etcd-turbulence]
      trigger: true
  - task: deploy-bosh-lite-manifests
    file: mega-ci/scripts/ci/deploy-bosh-lite-manifests.yml
    config:
      params:
        BOSH_AWS_ACCESS_KEY_ID: {{infrastructure_account_aws_access_key_id}}
        BOSH_AWS_SECRET_ACCESS_KEY: {{infrastructure_account_aws_secret_access_key}}
        BOSH_LITE_SECURITY_GROUP: {{bosh_lite_security_group}}
        BOSH_LITE_SUBNET_ID: {{bosh_lite_subnet_id}}
        BOSH_LITE_NAME: bosh-lite-etcd
        BOSH_LITE_KEYPAIR: bosh-lite-etcd
        BOSH_LITE_PRIVATE_KEY_CONTENTS: {{bosh-lite-private-key}}
        MANIFESTS: "manifests/bosh-lite/3-node-with-ssl.yml manifests/bosh-lite/3-node-no-ssl.yml"
        DEPENDENCIES: "cloudfoundry-incubator/consul-release"

- name: deploy-aws-manifests
  public: true
  serial: true
  serial_groups: [EATS]
  plan:
  - aggregate:
    - get: mega-ci
    - get: consul-release
      resource: consul-release-master
    - get: release
      resource: etcd-release-develop
      passed: [test-etcd-turbulence]
      trigger: true
  - task: deploy-multi-az-no-ssl-manifest
    file: mega-ci/scripts/ci/deploy-aws-manifests/deploy-etcd-aws-manifests.yml
    config:
      params:
        BOSH_DIRECTOR: {{cf_bosh_director_url}}
        BOSH_USER: {{cf_bosh_user}}
        BOSH_PASSWORD: {{cf_bosh_password}}
        AWS_ACCESS_KEY_ID: {{mega_ci_account_aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{mega_ci_account_aws_secret_access_key}}
        AWS_DEFAULT_REGION: {{mega_ci_account_aws_region}}
        MANIFEST_PATH: manifests/aws/multi-az-no-ssl.yml
  - task: deploy-multi-az-ssl-manifest
    file: mega-ci/scripts/ci/deploy-aws-manifests/deploy-etcd-aws-manifests.yml
    config:
      params:
        BOSH_DIRECTOR: {{cf_bosh_director_url}}
        BOSH_USER: {{cf_bosh_user}}
        BOSH_PASSWORD: {{cf_bosh_password}}
        AWS_ACCESS_KEY_ID: {{mega_ci_account_aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{mega_ci_account_aws_secret_access_key}}
        AWS_DEFAULT_REGION: {{mega_ci_account_aws_region}}
        MANIFEST_PATH: manifests/aws/multi-az-ssl.yml

- name: test-etcd-proxy
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      passed: [check-git-submodules]
      trigger: true
  - task: test-etcd-proxy
    file: mega-ci/scripts/ci/test-etcd-proxy/task.yml

- name: test-etcd-metrics-server
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      passed: [test-etcd-proxy]
      trigger: true
  - task: test-etcd-metrics-server
    file: mega-ci/scripts/ci/test-etcd-metrics-server/test.yml

- name: compile-etcd-develop
  public: true
  serial_groups: [EATS]
  plan:
  - aggregate:
    - get: mega-ci
    - get: stemcell
      resource: aws-stemcell
    - get: release-repo
      resource: etcd-release-develop
      passed: [test-etcd-metrics-server]
      trigger: true
  - task: compile-etcd-develop
    file: mega-ci/scripts/ci/compile-bosh-release/task-release-from-repo.yml
    config:
      params:
        BOSH_DIRECTOR: {{cf_bosh_director}}
        BOSH_USER: {{cf_bosh_user}}
        BOSH_PASSWORD: {{cf_bosh_password}}
        BOSH_DIRECTOR_CA_CERT: {{bosh_director_ca_cert}}
        RELEASE_NAME: etcd
  - put: compiled-etcd-release
    params:
      file: compiled-bosh-release/*.tgz

- name: compile-consul-release
  public: true
  serial_groups: [EATS]
  plan:
  - aggregate:
    - get: mega-ci
    - get: stemcell
      resource: aws-stemcell
      trigger: true
    - get: bosh-release
      resource: consul-release
      trigger: true
  - task: compile-bosh-release
    file: mega-ci/scripts/ci/compile-bosh-release/task.yml
    config:
      params:
        BOSH_DIRECTOR: {{cf_bosh_director}}
        BOSH_USER: {{cf_bosh_user}}
        BOSH_PASSWORD: {{cf_bosh_password}}
        BOSH_DIRECTOR_CA_CERT: {{bosh_director_ca_cert}}
        RELEASE_NAME: consul
  - put: compiled-consul-release
    params:
      file: compiled-bosh-release/*.tgz

- name: test-etcd
  public: true
  serial: true
  serial_groups: [EATS]
  plan:
  - aggregate:
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      passed: [compile-etcd-develop]
      trigger: true
    - get: compiled-etcd-release
      passed: [compile-etcd-develop]
    - get: consul-release
      passed: [compile-consul-release]
      resource: compiled-consul-release
  - task: run-eats
    file: mega-ci/scripts/ci/run-eats/task.yml
    config:
      params:
        BOSH_ENVIRONMENT: {{cf_bosh_director_url}}
        BOSH_CLIENT: {{cf_bosh_user}}
        BOSH_CLIENT_SECRET: {{cf_bosh_password}}
        BOSH_DIRECTOR: {{cf_bosh_director}}
        BOSH_USER: {{cf_bosh_user}}
        BOSH_PASSWORD: {{cf_bosh_password}}
        BOSH_CA_CERT: {{bosh_director_ca_cert}}
        AWS_SUBNET: {{mega_ci_account_aws_subnet}}
        AWS_ACCESS_KEY_ID: {{mega_ci_account_aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{mega_ci_account_aws_secret_access_key}}
        AWS_DEFAULT_KEY_NAME: {{mega_ci_account_aws_default_key_name}}
        AWS_DEFAULT_SECURITY_GROUPS: {{mega_ci_account_aws_default_security_groups}}
        AWS_REGION: {{mega_ci_account_aws_region}}
        PARALLEL_NODES: 5

- name: test-etcd-turbulence
  public: true
  serial: true
  serial_groups: [EATS]
  plan:
  - aggregate:
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      passed: [test-etcd]
      trigger: true
    - get: turbulence-release
    - get: bosh-aws-cpi-release
    - get: compiled-etcd-release
      passed: [test-etcd]
    - get: consul-release
      passed: [test-etcd]
      resource: compiled-consul-release
  - task: run-turbulence-test
    file: mega-ci/scripts/ci/run-eats/task-turbulence.yml
    config:
      params:
        BOSH_DIRECTOR: {{cf_bosh_director}}
        BOSH_USER: {{cf_bosh_user}}
        BOSH_PASSWORD: {{cf_bosh_password}}
        BOSH_DIRECTOR_CA_CERT: {{bosh_director_ca_cert}}
        AWS_SUBNET: {{mega_ci_account_aws_subnet}}
        AWS_ACCESS_KEY_ID: {{mega_ci_account_aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{mega_ci_account_aws_secret_access_key}}
        AWS_DEFAULT_KEY_NAME: {{mega_ci_account_aws_default_key_name}}
        AWS_DEFAULT_SECURITY_GROUPS: {{mega_ci_account_aws_default_security_groups}}
        AWS_REGION: {{mega_ci_account_aws_region}}
        REGISTRY_HOST: {{registry_host}}
        REGISTRY_PORT: {{registry_port}}
        REGISTRY_USERNAME: {{registry_username}}
        REGISTRY_PASSWORD: {{registry_password}}
        PARALLEL_NODES: 1

- name: deploy-with-cf
  public: true
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: etcd-cf-env
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      passed: [test-etcd-turbulence]
      trigger: true
    - get: cf-release
    - get: stemcell
      resource: aws-stemcell
  - task: deploy-etcd-cf
    file: mega-ci/scripts/ci/deploy-etcd-cf/task.yml
    config:
      params:
        BOSH_ENVIRONMENT: {{etcd_cf_bosh_environment}}
        BOSH_CLIENT: {{etcd_cf_bosh_client}}
        BOSH_CLIENT_SECRET: {{etcd_cf_bosh_client_secret}}
        BOSH_CA_CERT: {{etcd_cf_bosh_ca_cert}}
        CF_DEPLOYMENT_TRACE: true

- name: deploy-with-diego
  public: true
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: etcd-cf-env
    - get: mega-ci
    - get: diego-release
      resource: diego-release-master
    - get: etcd-release
      resource: etcd-release-develop
      passed: [deploy-with-cf]
      trigger: true
    - get: stemcell
      resource: aws-stemcell
  - task: deploy-etcd-diego
    file: mega-ci/scripts/ci/deploy-etcd-diego/task.yml
    config:
      params:
        BOSH_DIRECTOR: {{etcd_cf_bosh_environment}}
        BOSH_USER: {{etcd_cf_bosh_client}}
        BOSH_PASSWORD: {{etcd_cf_bosh_client_secret}}

- name: test-with-diego
  public: true
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      passed: [deploy-with-diego]
      trigger: true
  - task: run-cats
    file: mega-ci/scripts/ci/test-diego/task.yml
    config:
      params:
        CF_DOMAIN: {{etcd_cf_domain}}
        CF_USER: {{etcd_cf_user}}
        CF_PASSWORD: {{etcd_cf_password}}
        BOSH_DIRECTOR: {{etcd_cf_bosh_environment}}
        BOSH_USER: {{etcd_cf_bosh_client}}
        BOSH_PASSWORD: {{etcd_cf_bosh_client_secret}}
        DEPLOYMENT_NAME: etcd-cf-deployment

- name: test-cf-tls-upgrade
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      passed: [test-with-diego]
      trigger: true
  - task: run-cf-tls-upgrade-test
    file: mega-ci/scripts/ci/test-cf-tls-upgrade/task.yml
    config:
      params:
        CF_DOMAIN: {{etcd_cf_domain}}
        CF_USER: {{etcd_cf_user}}
        CF_PASSWORD: {{etcd_cf_password}}
        BOSH_DIRECTOR: {{etcd_cf_bosh_environment}}
        BOSH_USER: {{etcd_cf_bosh_client}}
        BOSH_PASSWORD: {{etcd_cf_bosh_client_secret}}
        DEPLOYMENT_NAME: etcd-cf-deployment

- name: delete-deployments
  public: true
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: mega-ci
    - get: etcd-release
      resource: etcd-release-develop
      passed:
      - test-cf-tls-upgrade
      trigger: true
  - task: delete-deployments
    file: mega-ci/scripts/ci/delete-deployments/task.yml
    config:
      params:
        DEPLOYMENTS_WITH_WORD: etcd-cf-deployment
        BOSH_DIRECTOR: {{etcd_cf_bosh_environment}}
        BOSH_USER: {{etcd_cf_bosh_client}}
        BOSH_PASSWORD: {{etcd_cf_bosh_client_secret}}

- name: create-final-release
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: oss-s3-buckets-stack
      resource: oss-s3-buckets-stack
    - get: release-repo
      resource: etcd-release-develop
      passed: [delete-deployments]
      trigger: true
    - get: release-repo-master
      resource: etcd-release-master
  - task: create-final-release
    file: mega-ci/scripts/ci/create-final-release/task.yml
    config:
      params:
        RELEASE_NAME: etcd
  - put: etcd-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v


- name: merge-master-into-develop
  public: true
  serial: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: release-repo-master
      resource: etcd-release-master
      trigger: true
    - get: release-repo
      resource: etcd-release-merge-target
  - task: merge-master-into-develop
    file: mega-ci/scripts/ci/merge-master-into-develop/task.yml
  - put: etcd-release-merge-target
    params:
      repository: final-release-repo
