groups:
- name: infrastructure
  jobs:
  - deploy-mega-ci-bosh

resources:
- name: deployments-runtime
  type: git
  source:
    branch: master
    private_key: {{deployments-runtime-private-key}}
    uri: git@github.com:cloudfoundry/deployments-runtime.git
- name: mega-ci
  type: git
  source:
    branch: master
    private_key: {{mega-ci-private-key}}
    uri: git@github.com:cloudfoundry/mega-ci.git

jobs:
- name: deploy-mega-ci-bosh
  public: true
  plan:
  - aggregate:
    - get: deployments-runtime
    - get: mega-ci
  - task: deploy-bosh
    file: mega-ci/scripts/ci/deploy-bosh.yml
    config:
      params:
        DEPLOYMENT_DIR: 'deployments-runtime/mega-ci'
