groups:
- name: infrastructure
  jobs:
  - deploy-mega-ci-bosh

resources:
- name: deployments-runtime
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/deployments-runtime.git
- name: mega-test-deployments
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/mega-test-deployments.git

jobs:
- name: deploy-mega-ci-bosh
  plan:
  - aggregate:
    - get: deployments-runtime
    - get: mega-test-deployments
  - task: deploy-bosh
    file: deployments-runtime/mega-ci/scripts/ci/deploy-bosh.yml
    config:
      params:
        DEPLOYMENT_DIR: 'mega-test'
