---
resources:
- name: mega-ci-master
  type: git
  source:
    uri: https://github.com/cloudfoundry/mega-ci
    branch: master

- name: mega-ci-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/mega-ci
    branch: master
    paths:
    - Dockerfile

- name: mega-ci-docker-image
  type: docker-image
  source:
    repository: cloudfoundry/mega-ci
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

jobs:
- name: mega-ci-docker-image
  plan:
  - do:
    - get: mega-ci
      resource: mega-ci-dockerfile
      trigger: true
    - put: mega-ci-docker-image
      params:
        build: mega-ci
        cache: true

- name: mega-ci-unit-tests
  public: true
  plan:
  - do:
    - get: mega-ci
      resource: mega-ci-master
      trigger: true
    - task: mega-ci-tests
      file: mega-ci/scripts/ci/test.yml


