---
resources:
- name: mega-ci-master
  type: git
  source:
    uri: https://github.com/cloudfoundry/mega-ci
    branch: master

- name: deployment-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/mega-ci
    branch: master
    paths:
    - dockerfiles/deployment

- name: bosh-bootloader-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/mega-ci
    branch: master
    paths:
    - dockerfiles/bosh-bootloader

- name: golang-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/mega-ci
    branch: master
    paths:
    - dockerfiles/golang

- name: vagrant-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/mega-ci
    branch: master
    paths:
    - dockerfiles/vagrant

- name: minimal-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/mega-ci
    branch: master
    paths:
    - dockerfiles/minimal

- name: golang-docker-image
  type: docker-image
  source:
    repository: cfinfrastructure/golang
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: bosh-bootloader-docker-image
  type: docker-image
  source:
    repository: cfinfrastructure/bosh-bootloader
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: deployment-docker-image
  type: docker-image
  source:
    repository: cfinfrastructure/deployment
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: minimal-docker-image
  type: docker-image
  source:
    repository: cfinfrastructure/minimal
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: vagrant-docker-image
  type: docker-image
  source:
    repository: cfinfrastructure/vagrant
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

jobs:
- name: deployment-docker-image
  plan:
  - do:
    - get: mega-ci
      resource: deployment-dockerfile
      trigger: true
    - put: deployment-docker-image
      params:
        build: mega-ci/dockerfiles/deployment
        cache: true

- name: golang-docker-image
  plan:
  - do:
    - get: mega-ci
      resource: golang-dockerfile
      trigger: true
    - put: golang-docker-image
      params:
        build: mega-ci/dockerfiles/golang
        cache: true

- name: bosh-bootloader-docker-image
  plan:
  - do:
    - get: mega-ci
      resource: bosh-bootloader-dockerfile
      trigger: true
    - put: bosh-bootloader-docker-image
      params:
        build: mega-ci/dockerfiles/bosh-bootloader
        cache: true

- name: minimal-docker-image
  plan:
  - do:
    - get: mega-ci
      resource: minimal-dockerfile
      trigger: true
    - put: minimal-docker-image
      params:
        build: mega-ci/dockerfiles/minimal
        cache: true

- name: vagrant-docker-image
  plan:
  - do:
    - get: mega-ci
      resource: vagrant-dockerfile
      trigger: true
    - put: vagrant-docker-image
      params:
        build: mega-ci/dockerfiles/vagrant
        cache: true

- name: mega-ci-unit-tests
  public: true
  plan:
  - do:
    - get: mega-ci
      resource: mega-ci-master
      trigger: true
    - task: mega-ci-tests
      file: mega-ci/scripts/ci/test.yml


