---
resources:
- name: mega-ci-master
  type: git
  source:
    uri: https://github.com/cloudfoundry/mega-ci
    branch: master

- name: mega-ci-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/mega-ci
    branch: master
    paths:
    - dockerfiles/mega-ci

- name: bosh-bootloader-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/mega-ci
    branch: master
    paths:
    - dockerfiles/bosh-bootloader

- name: gomegamatchers-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/mega-ci
    branch: master
    paths:
    - dockerfiles/gomegamatchers

- name: destiny-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/mega-ci
    branch: master
    paths:
    - dockerfiles/destiny

- name: bosh-test-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/mega-ci
    branch: master
    paths:
    - dockerfiles/bosh-test

- name: destiny-docker-image
  type: docker-image
  source:
    repository: cfinfrastructure/destiny
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: bosh-bootloader-docker-image
  type: docker-image
  source:
    repository: cfinfrastructure/bosh-bootloader
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: bosh-test-docker-image
  type: docker-image
  source:
    repository: cfinfrastructure/bosh-test
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: gomegamatchers-docker-image
  type: docker-image
  source:
    repository: cfinfrastructure/gomegamatchers
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: mega-ci-docker-image
  type: docker-image
  source:
    repository: cfinfrastructure/mega-ci
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

jobs:
- name: mega-ci-docker-image
  plan:
  - do:
    - get: mega-ci
      resource: mega-ci-dockerfile 
      trigger: true
    - put: mega-ci-docker-image
      params:
        build: mega-ci/dockerfiles/mega-ci
        cache: true
- name: destiny-docker-image
  plan:
  - do:
    - get: mega-ci
      resource: destiny-dockerfile
      trigger: true
    - put: destiny-docker-image
      params:
        build: mega-ci/dockerfiles/destiny
        cache: true
- name: gomegamatchers-docker-image
  plan:
  - do:
    - get: mega-ci
      resource: gomegamatchers-dockerfile
      trigger: true
    - put: gomegamatchers-docker-image
      params:
        build: mega-ci/dockerfiles/gomegamatchers
        cache: true
- name: bosh-bootloader-docker-image
  plan:
  - do:
    - get: mega-ci
      resource: bosh-bootloader-dockerfile
      trigger: true
    - put: bosh-bootloader-docker-image
      params:
        build: mega-ci/dockerfiles/bosh-bootloader
        cache: true
- name: bosh-test-docker-image
  plan:
  - do:
    - get: mega-ci
      resource: bosh-test-dockerfile
      trigger: true
    - put: bosh-test-docker-image
      params:
        build: mega-ci/dockerfiles/bosh-test
        cache: true

- name: mega-ci-unit-tests
  public: true
  plan:
  - do:
    - get: mega-ci
      resource: mega-ci-master
      trigger: true
    - task: mega-ci-tests
      file: mega-ci/scripts/ci/test.yml


