groups:
- name: multierror
  jobs:
  - test-multierror
resources:
- name: mega-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/mega-ci.git
- name: multierror-master
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/multierror.git
jobs:
- name: test-multierror
  public: true
  plan:
  - aggregate:
    - get: multierror
      resource: multierror-master
      trigger: true
    - get: mega-ci
  - task: run-tests
    file: mega-ci/scripts/ci/multierror-tests/task.yml
