groups:
- name: release
  jobs:
  - announce-rc
  - create-release-notes

resources:
- name: mega-pm-tools
  type: git
  source:
    branch: master
    uri: https://github.com/Amit-PivotalLabs/mega-pm-tools
- name: cf-release-repo-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/cf-release
- name: cf-github-release
  type: github-release
  source:
    user: cloudfoundry
    repository: cf-release
    access_token: {{release_candidate_bot_github_access_token}}
- name: cf-final-bosh-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-release

jobs:
- name: announce-rc
  public: true
  plan:
  - aggregate:
    - get: mega-pm-tools
    - get: cf-release-repo-develop
    - get: cf-github-release
  - task: announce-rc
    file: mega-pm-tools/announce-rc.yml
    config:
      params:
        GH_ACCESS_TOKEN: {{release_candidate_bot_github_access_token}}
- name: create-release-notes
  public: true
  plan:
  - aggregate:
    - get: cf-final-bosh-release
      trigger: true
    - get: mega-pm-tools
  - task: create-release-notes-template
    file: mega-pm-tools/create-release-notes-template.yml
    config:
      params:
        GH_ACCESS_TOKEN: {{release_notes_bot_github_access_token}}
  - task: request-pm-input
    file: mega-pm-tools/request-pm-input.yml
    config:
      params:
        TRACKER_API_TOKEN: {{tracker_api_token}}
        MEGA_PM_ID: {{mega_pm_id}}
