---
name: concourse

director_uuid: (( merge ))

releases:
  - name: concourse
    version: latest
  - name: garden-linux
    version: latest

networks:
  - name: concourse
    type: manual
    subnets:
      - range: 10.0.17.0/24
        reserved: [10.0.17.2 - 10.0.17.9]
        static: [10.0.17.31]
        dns: [10.0.0.2]
        gateway: 10.0.17.1
        cloud_properties:
          security_groups:
            - (( .cloud_properties.security_group_name ))
          subnet: (( .cloud_properties.subnet_id ))

jobs:
  - name: discovery
    instances: 1
    resource_pool: discovery
    persistent_disk: 1024
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: blackbox}
    networks:
      - name: concourse
        static_ips: (( .networks.concourse.subnets.[0].static ))
    properties:
      consul:
        agent:
          mode: server

  - name: atc
    instances: 2
    resource_pool: orchestration
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: blackbox}
      - {release: concourse, name: atc}
      - {release: concourse, name: tsa}
    networks:
      - name: concourse
    update:
      serial: true
      max_in_flight: 1
    properties:
      atc:
        basic_auth_username: (( atc_credentials.basic_auth_username ))
        basic_auth_password: (( atc_credentials.basic_auth_password ))
        publicly_viewable: true
        postgresql:
          database: (( atc_credentials.db_name ))
          role:
            name: (( atc_credentials.db_user ))
            password: ((atc_credentials.db_password ))
      tsa:
        atc:
          username: (( atc_credentials.basic_auth_username ))
          password: (( atc_credentials.basic_auth_password ))
      consul:
        agent:
          servers: {lan: (( jobs.discovery.networks.concourse.static_ips ))}

  - name: postgresql
    instances: 1
    resource_pool: databases
    persistent_disk: 102400
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: blackbox}
      - {release: concourse, name: postgresql}
    networks: [{name: concourse}]
    properties:
      postgresql:
        databases:
        - name: (( atc_credentials.db_name ))
        roles:
        - name: (( atc_credentials.db_user ))
          password: ((atc_credentials.db_password ))
      consul:
        agent:
          servers: {lan: (( jobs.discovery.networks.concourse.static_ips ))}

  - name: worker
    instances: 6
    resource_pool: workers
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: blackbox}
      - {release: concourse, name: groundcrew}
      - {release: garden-linux, name: garden}
    networks: [{name: concourse}]
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        default_container_grace_time: 15m
        btrfs_store_size_mb: 100000
      consul:
        agent:
          servers: {lan: (( jobs.discovery.networks.concourse.static_ips ))}

resource_pools:
  - name: orchestration
    network: concourse
    stemcell: &stemcell
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: c3.large
      availability_zone: (( .cloud_properties.az ))
      elbs:
       - (( .cloud_properties.load_balancer ))

  - name: databases
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: c3.xlarge
      availability_zone: (( .cloud_properties.az ))

  - name: workers
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: c3.xlarge
      availability_zone: (( .cloud_properties.az ))
      ephemeral_disk:
        size: 1024000
        type: gp2

  - name: discovery
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( .cloud_properties.az ))

compilation:
  workers: 4
  network: concourse
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: c3.large
    availability_zone: (( .cloud_properties.az ))

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

cloud_properties: (( merge ))
atc_credentials: (( merge ))
