#!/bin/bash -exu

export ROOT="${PWD}"
export ETCD_RELEASE_VERSION="$(ls compiled-etcd-release/*.tgz | sed 's/compiled-etcd-release\/release-etcd-\(.*\)-on-ubuntu.*/\1/')"

function main() {
  mkdir -p $GOPATH/src/github.com/cloudfoundry-incubator
  pushd $GOPATH/src/github.com/cloudfoundry-incubator > /dev/null
    ln -s $ROOT/etcd-release
  popd > /dev/null

  upload_releases
  write_configuration

  pushd $GOPATH/src/github.com/cloudfoundry-incubator/etcd-release > /dev/null
    EATS_CONFIG=$PWD/../eats_config.json ./src/acceptance-tests/scripts/test -nodes "${PARALLEL_NODES}" turbulence
  popd > /dev/null
}

function write_configuration() {
  cat > eats_config.json <<EOF
  {
    "bosh": {
      "target": "$BOSH_DIRECTOR",
      "username": "$BOSH_USER",
      "password": "$BOSH_PASSWORD",
      "director_ca_cert": "$(set +x; rollup "${BOSH_DIRECTOR_CA_CERT}")"
    },
    "aws": {
      "subnet": "$AWS_SUBNET",
      "access_key_id": "$AWS_ACCESS_KEY_ID",
      "secret_access_key": "$AWS_SECRET_ACCESS_KEY",
      "default_key_name": "$AWS_DEFAULT_KEY_NAME",
      "default_security_groups": ["$AWS_DEFAULT_SECURITY_GROUPS"],
      "region": "$AWS_REGION"
    },
    "registry": {
      "host": "$REGISTRY_HOST",
      "port": $REGISTRY_PORT,
      "username": "$REGISTRY_USERNAME",
      "password": "$REGISTRY_PASSWORD"
    }
  }
EOF
}


function upload_releases() {
  pushd "${ROOT}/compiled-etcd-release" > /dev/null
    /opt/rubies/ruby-2.2.4/bin/bosh -t "${BOSH_DIRECTOR}" -n upload release release-*.tgz
  popd > /dev/null

  pushd "${ROOT}/consul-release" > /dev/null
    /opt/rubies/ruby-2.2.4/bin/bosh -t "${BOSH_DIRECTOR}" upload release release-*.tgz --skip-if-exists
  popd > /dev/null

  pushd "${ROOT}/turbulence-release" > /dev/null
    /opt/rubies/ruby-2.2.4/bin/bosh -t "${BOSH_DIRECTOR}" upload release release.tgz --skip-if-exists
  popd > /dev/null

  pushd "${ROOT}/bosh-aws-cpi-release" > /dev/null
    /opt/rubies/ruby-2.2.4/bin/bosh -t "${BOSH_DIRECTOR}" upload release release.tgz --skip-if-exists
  popd > /dev/null
}

function cleanup_releases() {
  /opt/rubies/ruby-2.2.4/bin/bosh -t "${BOSH_DIRECTOR}" -n cleanup
}

function rollup() {
  set +x
  local input
  input="${1}"

  local output

  IFS=$'\n'
  for line in ${input}; do
    output="${output:-""}\n${line}"
  done

  printf "%s" "${output#'\n'}"
  set -x
}

trap cleanup_releases EXIT
main
