#!/bin/bash -exu

export ROOT="${PWD}"
export GOPATH="$PWD/etcd-release"
export GO15VENDOREXPERIMENT=1
export ETCD_RELEASE_VERSION="99999+dev.$(date +%s)"

function main() {
  upload_stemcell
  upload_releases
  write_configuration
  force_compilation

  pushd etcd-release > /dev/null
    EATS_CONFIG=$PWD/../eats_config.json ./src/acceptance-tests/scripts/test -nodes "${PARALLEL_NODES}"
  popd > /dev/null
}

function force_compilation() {
  pushd /tmp > /dev/null
    sed \
      -e "s/REPLACE_ME_DIRECTOR_UUID/$(bosh -t "${BOSH_DIRECTOR}" status --uuid)/g" \
      -e "s/REPLACE_ME_ETCD_VERSION/${ETCD_RELEASE_VERSION}/g" \
      "${ROOT}/mega-ci/scripts/ci/run-eats/fixtures/etcd_compilation.yml" > "etcd_compilation.yml"

    bosh -t "${BOSH_DIRECTOR}" -d "etcd_compilation.yml" -n deploy
    bosh -t "${BOSH_DIRECTOR}" -d "etcd_compilation.yml" export release "etcd/${ETCD_RELEASE_VERSION}" "ubuntu-trusty/${STEMCELL_VERSION}"
    bosh -t "${BOSH_DIRECTOR}" -d "etcd_compilation.yml" -n delete deployment etcd-compilation
  popd > /dev/null
}

function write_configuration() {
  cat > eats_config.json <<EOF
  {
    "bosh": {
      "target": "$BOSH_DIRECTOR",
      "username": "$BOSH_USER",
      "password": "$BOSH_PASSWORD",
      "director_ca_cert": "$(set +x; rollup "${BOSH_DIRECTOR_CA_CERT}")"
    },
    "aws": {
      "subnet": "$AWS_SUBNET",
      "access_key_id": "$AWS_ACCESS_KEY_ID",
      "secret_access_key": "$AWS_SECRET_ACCESS_KEY",
      "default_key_name": "$AWS_DEFAULT_KEY_NAME",
      "default_security_groups": ["$AWS_DEFAULT_SECURITY_GROUPS"],
      "region": "$AWS_REGION"
    },
    "registry": {
      "host": "$REGISTRY_HOST",
      "port": $REGISTRY_PORT,
      "username": "$REGISTRY_USERNAME",
      "password": "$REGISTRY_PASSWORD"
    }
  }
EOF
}


function upload_releases() {
  pushd "${ROOT}/etcd-release" > /dev/null
    bosh -t "${BOSH_DIRECTOR}" -n create release --force --version "${ETCD_RELEASE_VERSION}"
    bosh -t "${BOSH_DIRECTOR}" -n upload release
  popd > /dev/null

  pushd "${ROOT}/turbulence-release" > /dev/null
    bosh -t "${BOSH_DIRECTOR}" upload release release.tgz --skip-if-exists
  popd > /dev/null

  pushd "${ROOT}/bosh-aws-cpi-release" > /dev/null
    bosh -t "${BOSH_DIRECTOR}" upload release release.tgz --skip-if-exists
  popd > /dev/null

  pushd "${ROOT}/consul-release" > /dev/null
    bosh -t "${BOSH_DIRECTOR}" upload release release.tgz --skip-if-exists
  popd > /dev/null
}

function cleanup_releases() {
  bosh -t "${BOSH_DIRECTOR}" -n cleanup
}

function rollup() {
  set +x
  local input
  input="${1}"

  local output

  IFS=$'\n'
  for line in ${input}; do
    output="${output:-""}\n${line}"
  done

  printf "%s" "${output#'\n'}"
  set -x
}

trap cleanup_releases EXIT
main
