---
name: concourse

# replace with bosh status --uuid
director_uuid: (( merge )) 

# pick a sane password
atc_db_role: &atc-db-role
  name: atc
  password: bF5GsAugkE6b07TAm5ITWtF9Peh5qDXB 

# replace all addresses with your VPC range
#
# e.g. X.X.0.2 -> 10.10.0.2
networks: (( merge ))

# replace with an AZ from your account
aws_config: (( merge ))

#merge our secrets in
secrets: (( merge ))

releases:
  - name: concourse
    version: latest
  - name: garden-linux
    version: latest

jobs:
  - name: discovery
    instances: 1
    resource_pool: discovery
    persistent_disk: 1024
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: blackbox}
    networks:
      - name: concourse
        static_ips: (( .networks.concourse.subnets.[0].static ))
    properties:
      blackbox:
        expvar:
          datadog:
            api_key: (( secrets.blackbox.datadog_api_key ))
        syslog:
          destination:
            address: (( secrets.blackbox.syslog_address ))
            transport: (( secrets.blackbox.syslog_transport ))
      consul:
        agent:
          mode: server

  - name: atc
    instances: 2
    resource_pool: orchestration
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: blackbox}
      - {release: concourse, name: atc}
      - {release: concourse, name: tsa}
    networks:
      - name: concourse
    update:
      serial: true
      max_in_flight: 1
    properties:
      blackbox:
        expvar:
          datadog:
            api_key: (( secrets.blackbox.datadog_api_key ))
        syslog:
          destination:
            address: (( secrets.blackbox.syslog_address ))
            transport: (( secrets.blackbox.syslog_transport ))
      atc:
        basic_auth_username: (( secrets.atc.username ))
        basic_auth_password: (( secrets.atc.password ))
        publicly_viewable: true
        postgresql:
          database: (( secrets.atc.database_name ))
          role:
            name: (( secrets.atc.database_user ))
            password: ((secrets.atc.database_password ))
      tsa: 
        host_key: (( secrets.tsa.private_key ))
        authorized_keys: (( secrets.tsa.authorized_keys ))
        atc:
          username: (( secrets.atc.username ))
          password: (( secrets.atc.password ))

      consul:
        agent:
          servers: {lan: (( jobs.discovery.networks.concourse.static_ips ))}

  - name: postgresql
    instances: 1
    resource_pool: databases
    persistent_disk: 102400
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: blackbox}
      - {release: concourse, name: postgresql}
    networks: [{name: concourse}]
    properties:
      blackbox:
        expvar:
          datadog:
            api_key: (( secrets.blackbox.datadog_api_key ))
        syslog:
          destination:
            address: (( secrets.blackbox.syslog_address ))
            transport: (( secrets.blackbox.syslog_transport ))

      postgresql:
        databases: 
        - name: (( secrets.atc.database_name ))
        roles: 
        - name: (( secrets.atc.database_user ))
          password: ((secrets.atc.database_password ))

      consul:
        agent:
          servers: {lan: (( jobs.discovery.networks.concourse.static_ips ))}

  - name: worker
    instances: 6
    resource_pool: workers
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: blackbox}
      - {release: concourse, name: groundcrew}
      - {release: garden-linux, name: garden}
    networks: [{name: concourse}]
    properties:
      blackbox:
        expvar:
          datadog:
            api_key: (( secrets.blackbox.datadog_api_key ))
        syslog:
          destination:
            address: (( secrets.blackbox.syslog_address ))
            transport: (( secrets.blackbox.syslog_transport ))

      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        default_container_grace_time: 15m
        btrfs_store_size_mb: 100000

      groundcrew:
        tsa:
          host_public_key: (( secrets.tsa.public_key ))

      consul:
        agent:
          servers: {lan: (( jobs.discovery.networks.concourse.static_ips ))}

resource_pools:
  - name: orchestration
    network: concourse
    stemcell: &stemcell
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: c3.large
      availability_zone: (( aws_config.az ))
      elbs: [(( aws_config.load_balancer ))]

  - name: databases
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: c3.xlarge
      availability_zone: (( aws_config.az ))

  - name: workers
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: c3.xlarge
      availability_zone: (( aws_config.az ))
      ephemeral_disk:
        size: 1024000
        type: gp2

  - name: discovery
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( aws_config.az ))

compilation:
  workers: 4
  network: concourse
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: c3.large
    availability_zone: (( aws_config.az ))

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
