#!/bin/sh

set -eux

add_mega_ci_to_gopath() {
  mkdir -p $GOPATH/src/github.com/cloudfoundry
  ln -s "${root_dir}" $GOPATH/src/github.com/cloudfoundry/
}

add_candiedyaml_to_gopath() {
  mkdir -p ${root_dir}/src/github.com/cloudfoundry-incubator
  ln -s "${root_dir}/scripts/ci/deploy-aws-manifests/vendor/github.com/cloudfoundry-incubator/candiedyaml" ${root_dir}/src/github.com/cloudfoundry-incubator/candiedyaml
}

main() {
  root_dir=$(cd "$(dirname $0)/.." && pwd)

  add_mega_ci_to_gopath
  add_candiedyaml_to_gopath

  export GOPATH=$root_dir:$GOPATH
  export PATH=$root_dir/bin:$PATH
  export GO15VENDOREXPERIMENT=1

  # install ginkgo
  go install -v github.com/onsi/ginkgo/ginkgo

  ginkgo \
      -p \
      -r \
      -race \
      -randomizeAllSpecs \
      -randomizeSuites \
      "$@" \
      .
}

main
