#!/bin/bash -exu

main() {
  ROOT="${PWD}"

  mkdir -p "${GOPATH}/src/github.com/cloudfoundry"
  pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
    ln -s "${ROOT}/mega-ci"
    pushd mega-ci > /dev/null
      export GO15VENDOREXPERIMENT=1
      ginkgo \
          -p \
          -r \
          -race \
          -randomizeAllSpecs \
          -randomizeSuites \
          "$@" \
          .
    popd > /dev/null
  popd > /dev/null
}

main
