#!/bin/sh

set -eux

root_dir=$(cd "$(dirname $0)/.." && pwd)

export GOPATH=$root_dir:$GOPATH
export PATH=$root_dir/bin:$PATH
export GO15VENDOREXPERIMENT=1

# install ginkgo
go install -v github.com/onsi/ginkgo/ginkgo

ginkgo \
    -p \
    -r \
    -race \
    -randomizeAllSpecs \
    -randomizeSuites \
    "$@" \
    .
