#!/bin/bash -exu

setup_ruby() {
  set +eu
  source /usr/local/share/chruby/chruby.sh
  chruby 2.2.4
  set -eu
}

generate_deployment_config() {
  local dir="${1}"
  local deployments_dir="${2}"
  local stubs="${@:3}"

  local stubs_array
  stubs_array="$(jq -n --arg v "${stubs}" '{ v: $v | split(" ") }' | jq -c .v)"

  local stemcell_location
  stemcell_location="$(ls "${dir}/stemcell/"*.tgz | head -n 1)"

  local etcd_location
  etcd_location="$(ls "${dir}/etcd-release/"*.tgz | head -n 1)"

  local consul_location
  consul_location="$(ls "${dir}/consul-release/"*.tgz | head -n 1)"

  cat <<CONFIG
{
	"cf": "${dir}/cf-release",
	"etcd": "${etcd_location}",
	"consul": "${consul_location}",
	"stemcell": "${stemcell_location}",
	"deployments-dir": "${deployments_dir}",
	"stubs": ${stubs_array}
}
CONFIG
}

deploy() {
  echo "bosh -n -t ${1} -u ${2} -p REDACTED -d ${4} deploy --redact-diff"

  bosh \
    -n \
    -t "${1}" \
    -u "${2}" \
    -p "${3}" \
    -d "${4}" \
    deploy \
    --redact-diff
}

main() {
  setup_ruby

  local stub_path
  stub_path="${PWD}/${STUB_PATH}"

  local stub_parts_path
  stub_parts_path="${PWD}/${STUB_PARTS_PATH}"

  local stubs
  stubs=("${stub_path} $(ls "${stub_parts_path}/"*)")

  generate_deployment_config \
	  "${PWD}" \
	  "${PWD}" \
	  ${stubs[@]} \
	  > "${PWD}/config.json"

  "${PWD}/cf-deployment/tools/prepare-deployments" \
	  "aws" \
	  "${PWD}/config.json"
set +x
  deploy \
    "${BOSH_DIRECTOR}" \
    "${BOSH_USER}" \
    "${BOSH_PASSWORD}" \
    "${PWD}/cf.yml"
set -x
}

if [ "$(basename "${0}")" = "task" ]; then
	main
fi
