---
director_uuid: REPLACE_ME_DIRECTOR_UUID

name: bbl_compilation

releases:
- name: bosh
  version: BOSH_VERSION

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: STEMCELL_VERSION

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

instance_groups: []
