---
meta:
  environment: REPLACE_WITH_DEPLOYMENT_NAME

cf_databases: (( merge ))
cf_resources: (( merge ))
cloud_formation_inputs: (( merge ))

director_uuid: (( merge ))

networks:
  - name: cf1
    type: manual
    subnets:
      - range: 10.0.15.0/24
        name: default_unused
        reserved:
          - 10.0.15.2 - 10.0.15.9
        static:
          - 10.0.15.10 - 10.0.15.100
        gateway: 10.0.15.1
        dns:
          - 10.0.0.2
        cloud_properties:
          security_groups: [(( cf_resources.security_group_name ))]
          subnet: (( cf_resources.subnets.[0].subnet_id ))

  - name: cf2
    type: manual
    subnets:
      - range: 10.0.16.0/24
        name: default_unused
        reserved:
          - 10.0.16.2 - 10.0.16.9
        static:
          - 10.0.16.10 - 10.0.16.100
        gateway: 10.0.16.1
        dns:
          - 10.0.0.2
        cloud_properties:
          security_groups: [(( cf_resources.security_group_name ))]
          subnet: (( cf_resources.subnets.[1].subnet_id ))
resource_pools:
  - name: router_z1
    cloud_properties:
      elbs: [(( cf_resources.elb ))]
  - name: router_z2
    cloud_properties:
      elbs: [(( cf_resources.elb ))]

properties:
  domain: (( cloud_formation_inputs.CFHostedZoneName ))
  ssl:
    skip_cert_verify: false # REPLACE_WITH true if your ELB is using a self signed cert
  system_domain_organization: system
  app_domains: [(( cloud_formation_inputs.CFAppsDomainHostedZoneName ))]
  template_only:
    aws:
      access_key_id: (( cf_resources.blobstore.access_key ))
      secret_access_key: (( cf_resources.blobstore.secret_key ))
      availability_zone: (( cf_resources.subnets.[0].availability_zone ))
      availability_zone2: (( cf_resources.subnets.[1].availability_zone ))

  ccdb:
    db_scheme: mysql
    roles:
    - tag: admin
      name: (( cloud_formation_inputs.CCDBUsername ))
      password: (( cloud_formation_inputs.CCDBPassword ))
    databases:
    - tag: cc
      name: (( cf_databases.ccdb_database ))
    address: (( cf_databases.ccdb_host ))
    port: (( cf_databases.ccdb_port ))
  uaadb:
    db_scheme: mysql
    roles:
    - tag: admin
      name: (( cloud_formation_inputs.UAADBUsername ))
      password: (( cloud_formation_inputs.UAADBPassword ))
    databases:
    - tag: uaa
      name: (( cf_databases.uaadb_database ))
    address: (( cf_databases.uaadb_host ))
    port: (( cf_databases.uaadb_port ))

  uaa:
    jwt:
      signing_key: |
        REPLACE_WITH_RSA_PRIVATE_KEY
      verification_key: |
        REPLACE_WITH_RSA_PUBLIC_KEY
    cc:
      client_secret: REPLACE_WITH_PASSWORD
    admin:
      client_secret: REPLACE_WITH_PASSWORD
    batch:
      username: REPLACE_WITH_USERNAME
      password: REPLACE_WITH_PASSWORD
    clients:
      login:
        secret: REPLACE_WITH_PASSWORD
      notifications:
        secret: REPLACE_WITH_PASSWORD
      doppler:
        secret: REPLACE_WITH_PASSWORD
      cloud_controller_username_lookup:
        secret: REPLACE_WITH_PASSWORD
      gorouter:
        secret: REPLACE_WITH_PASSWORD

    scim:
      users:
      - admin|REPLACE_WITH_ADMIN_USER_PASSWORD|scim.write,scim.read,openid,cloud_controller.admin,doppler.firehose

  nats:
    user: nats
    password: REPLACE_WITH_PASSWORD
    monitor_port: 9222

  cc:
    bulk_api_password: REPLACE_WITH_PASSWORD
    staging_upload_user: REPLACE_WITH_USERNAME
    staging_upload_password: REPLACE_WITH_PASSWORD
    db_encryption_key: REPLACE_WITH_PASSWORD
    resource_pool: ~
    droplets: ~

  router:
    status:
      user: router
      password: REPLACE_WITH_PASSWORD
    route_service_secret: REPLACE_WITH_PASSWORD

  loggregator_endpoint:
    shared_secret: REPLACE_WITH_PASSWORD

  dea_next:
    disk_mb: 199000
    memory_mb: 28001

  collector:
    deployment_name: (( meta.environment ))

  acceptance_tests:
    api:  (( "api." domain ))
    apps_domain: (( app_domains ))
    system_domain: (( domain ))
    client_secret: (( uaa.clients.gorouter.secret ))
    admin_user: admin
    admin_password: REPLACE_WITH_ADMIN_USER_PASSWORD
    nodes: 3
    include_sso: false
    include_services: false
    include_logging: false
    include_v3: false
    include_routing: false
    skip_ssl_validation: false # REPLACE_WITH true if your ELB is using a self signed cert
    use_diego: false
    use_http: true

  smoke_tests:
    api:  (( "api." domain ))
    apps_domain: (( app_domains ))
    user: admin
    password: REPLACE_WITH_ADMIN_USER_PASSWORD
    org: 'smoke-tests'
    space: 'smoke-tests'
    use_existing_org: true
    skip_ssl_validation: false # REPLACE_WITH true if your ELB is using a self signed cert

  consul:
    encrypt_keys: [REPLACE_WITH_CONSUL_ENCRYPTION_KEY]
    require_ssl: true
    ca_cert: |
      REPLACE_WITH_CONSUL_CA_CERT
    server_cert: |
      REPLACE_WITH_CONSUL_SERVER_CERT
    server_key: |
      REPLACE_WITH_CONSUL_SERVER_KEY
    agent_cert: |
      REPLACE_WITH_CONSUL_AGENT_CERT
    agent_key: |
      REPLACE_WITH_CONSUL_AGENT_KEY
jobs:
  - name: api_z2
    instances: 0
  - name: api_worker_z2
    instances: 0
  - name: consul_z1
    instances: 1
  - name: consul_z2
    instances: 0
  - name: doppler_z2
    instances: 0
  - name: etcd_z1
    instances: 1
  - name: etcd_z2
    instances: 0
  - name: hm9000_z2
    instances: 0
  - name: loggregator_trafficcontroller_z2
    instances: 0
  - name: nats_z2
    instances: 0
  - name: router_z2
    instances: 0
  - name: runner_z2
    instances: 0
  - name: smoke_tests
    instances: 1
  - name: stats_z2
    instances: 0
  - name: uaa_z2
    instances: 0
