#!/bin/bash
set -e -x

source ~/.bashrc

cd cf-canaries

# install the canaries application name
bundle
gem build cf_canaries.gemspec
gem install cf_canaries-0.1.3.gem


cf api $CF_API_ENDPOINT --skip-ssl-validation
set +x
echo "Authenticating as $CF_API_USER"
cf auth "$CF_API_USER" "$CF_API_PASSWORD"
echo "Succeeded authenticating"
set -x

set +e
cf create-org canaries
cf target -o canaries
cf create-space canaries
cf target -s canaries
set -e

set +x
echo "Running command:
canaries --number-of-zero-downtime-apps=1 \\
         --number-of-instances-canary-instances=2 \\
         --number-of-instances-per-app=2 \\
         --target=$CF_API_ENDPOINT \\
         --app-domain=$CF_APPS_DOMAIN \\
         --username=$CF_API_USER \\
         --password=\$CF_API_PASSWORD \\
         --organization=canaries \\
         --space=canaries \\
         --skip-ssl-validation"
canaries --number-of-zero-downtime-apps=1 \
         --number-of-instances-canary-instances=2 \
         --number-of-instances-per-app=2 \
         --target="$CF_API_ENDPOINT" \
         --app-domain="$CF_APPS_DOMAIN" \
         --username="$CF_API_USER" \
         --password="$CF_API_PASSWORD" \
         --organization=canaries \
         --space=canaries \
         --skip-ssl-validation
echo "Succeeded running command"
set -x
