#!/bin/bash -exu

function create_integration_config() {
  cat > eats_config.json <<EOF
  {
    "bosh":{
      "target": "${BOSH_DIRECTOR}",
      "username": "${BOSH_USER}",
      "password": "${BOSH_PASSWORD}",
      "deployment_name": "${DEPLOYMENT_NAME}"
    },
    "cf": {
      "domain": "${CF_DOMAIN}",
      "username": "${CF_USER}",
      "password": "${CF_PASSWORD}"
    }
  }
EOF
}

function main() {
  local ROOT=$1

  mkdir -p $GOPATH/src/github.com/cloudfoundry-incubator
  pushd $GOPATH/src/github.com/cloudfoundry-incubator > /dev/null
    ln -s $ROOT/etcd-release
  popd > /dev/null

  pushd $GOPATH/src/github.com/cloudfoundry-incubator/etcd-release > /dev/null
    create_integration_config
    EATS_CONFIG="${PWD}/eats_config.json" ginkgo \
      -r \
      -randomizeAllSpecs \
      -randomizeSuites \
      -failFast \
      -succinct \
      -slowSpecThreshold 300 \
      ./src/cf-tls-upgrade/
  popd > /dev/null
}

main "${PWD}"
